import os
from celery import Celery

redis_url = os.getenv("REDIS_URL", "redis://localhost:6379/0")

app = Celery("totalSimulation", broker=redis_url, backend=redis_url)

app.conf.update(
    task_serializer="json",
    result_serializer="json",
    accept_content=["json"],
    task_track_started=True,
    result_expires=3600,
    task_routes={
        "tools.rebound_tool.run_rebound": {"queue": "astro"},
        "tools.qutip_tool.run_qutip": {"queue": "quantum"},
        "tools.openmm_tool.run_openmm": {"queue": "molecular"},
        "tools.pyscf_tool.run_pyscf": {"queue": "electronic"},
        "tools.mdanalysis_tool.run_mdanalysis": {"queue": "analysis"},
        "tools.psi4_tool.run_psi4": {"queue": "electronic-psi4"},
        "tools.gromacs_tool.run_gromacs": {"queue": "molecular-gmx"},
        "tools.namd_tool.run_namd": {"queue": "molecular-namd"},
        "tools.qmmm_tool.run_qmmm": {"queue": "qmmm"},
        "tools.pybullet_tool.run_pybullet": {"queue": "mechanics"},
        "tools.einsteinpy_tool.run_einsteinpy": {"queue": "relativity"},
        "tools.nrpy_tool.run_nrpy": {"queue": "relativity-nrpy"},
        "tools.fenics_tool.run_fenics": {"queue": "continuum-fenics"},
        "tools.elmer_tool.run_elmer": {"queue": "continuum-elmer"},
        "tools.basico_tool.run_basico": {"queue": "sysbio"},
        "tools.tellurium_tool.run_tellurium": {"queue": "sysbio-tel"},
        "tools.brian2_tool.run_brian2": {"queue": "neuro"},
        "tools.nest_tool.run_nest": {"queue": "neuro-nest"},
        "tools.msprime_tool.run_msprime": {"queue": "evolution"},
        "tools.rdkit_tool.run_rdkit": {"queue": "chemistry"},
        "tools.cantera_tool.run_cantera": {"queue": "kinetics"},
        "tools.qe_tool.run_qe": {"queue": "materials-qe"},
        "tools.lammps_tool.run_lammps": {"queue": "materials-lammps"},
        "tools.sympy_tool.run_sympy": {"queue": "symbolic"},
        "tools.gmsh_tool.run_gmsh": {"queue": "mesh"},
        "tools.lcapy_tool.run_lcapy": {"queue": "symbolic-circuits"},
        "tools.pennylane_tool.run_pennylane": {"queue": "quantum-ml"},
        "tools.sagemath_tool.run_sagemath": {"queue": "math-sage"},
        "tools.lean4_tool.run_lean4": {"queue": "math-lean"},
        "tools.gap_tool.run_gap": {"queue": "math-gap"},
        "tools.pyspice_tool.run_pyspice": {"queue": "circuits-spice"},
        "tools.qiskit_tool.run_qiskit": {"queue": "circuits-qiskit"},
        "tools.matplotlib_tool.run_matplotlib": {"queue": "plotting"},
        "tools.control_tool.run_control": {"queue": "control"},
        "tools.pyomo_tool.run_pyomo": {"queue": "optimization"},
        "tools.networkx_tool.run_networkx": {"queue": "graph"},
        "tools.phiflow_tool.run_phiflow": {"queue": "diffphys"},
        "tools.manim_tool.run_manim": {"queue": "render-manim"},
        "tools.openfoam_tool.run_openfoam": {"queue": "cfd-foam"},
        "tools.dedalus_tool.run_dedalus": {"queue": "spectral-pde"},
        "tools.su2_tool.run_su2": {"queue": "cfd-su2"},
        "tools.firedrake_tool.run_firedrake": {"queue": "continuum-firedrake"},
        "tools.vtk_tool.run_vtk": {"queue": "rendering"},
        "tools.openbabel_tool.run_openbabel": {"queue": "cheminformatics"},
        "tools.comsol_stub.run_comsol": {"queue": "continuum-comsol"},
        "tools.alphafold_stub.run_alphafold": {"queue": "bio-alphafold"},
        "tools.slim_tool.run_slim": {"queue": "evolution-slim"},
        "tools.tskit_tool.run_tskit": {"queue": "evolution-tskit"},
        "tools.simupop_tool.run_simupop": {"queue": "evolution-simupop"},
        "tools.pyrosetta_stub.run_pyrosetta": {"queue": "bio-pyrosetta"},
        "tools.etk_tool.run_etk": {"queue": "astro-etk"},
    },
)

app.autodiscover_tasks(["tools"])
