import os
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    redis_url: str = "redis://localhost:6379/0"
    database_url: str = "postgresql+asyncpg://totalsim:totalsim_dev@localhost:5433/totalsimulation"
    database_url_sync: str = "postgresql+psycopg2://totalsim:totalsim_dev@localhost:5433/totalsimulation"
    results_dir: str = "/data/results"
    fastapi_host: str = "0.0.0.0"
    fastapi_port: int = 8000
    max_sweep_runs: int = 100
    max_pipeline_steps: int = 20
    export_dir: str = "/data/exports"
    auth_enabled: bool = False
    jwt_secret: str = "dev-secret-change-in-production"
    access_token_expire_minutes: int = 1440


settings = Settings()

# Tool registry — maps tool name to metadata
TOOL_REGISTRY = {
    "rebound": {
        "name": "REBOUND",
        "description": "N-body gravitational dynamics simulator",
        "layer": "astrophysics",
        "queue": "astro",
        "task": "tools.rebound_tool.run_rebound",
    },
    "qutip": {
        "name": "QuTiP",
        "description": "Quantum Toolbox in Python — quantum dynamics simulator",
        "layer": "quantum",
        "queue": "quantum",
        "task": "tools.qutip_tool.run_qutip",
    },
    "openmm": {
        "name": "OpenMM",
        "description": "GPU-accelerated molecular dynamics",
        "layer": "molecular",
        "queue": "molecular",
        "task": "tools.openmm_tool.run_openmm",
    },
    "pyscf": {
        "name": "PySCF",
        "description": "Electronic structure calculations (HF, DFT, MP2, CCSD)",
        "layer": "electronic",
        "queue": "electronic",
        "task": "tools.pyscf_tool.run_pyscf",
    },
    "mdanalysis": {
        "name": "MDAnalysis",
        "description": "Trajectory analysis and post-processing for MD simulations",
        "layer": "analysis",
        "queue": "analysis",
        "task": "tools.mdanalysis_tool.run_mdanalysis",
    },
    "psi4": {
        "name": "Psi4",
        "description": "Ab initio quantum chemistry with SAPT interaction analysis",
        "layer": "electronic",
        "queue": "electronic-psi4",
        "task": "tools.psi4_tool.run_psi4",
    },
    "gromacs": {
        "name": "GROMACS",
        "description": "High-performance molecular dynamics for biomolecular systems",
        "layer": "molecular",
        "queue": "molecular-gmx",
        "task": "tools.gromacs_tool.run_gromacs",
    },
    "namd": {
        "name": "NAMD",
        "description": "Scalable molecular dynamics for large biomolecular systems",
        "layer": "molecular",
        "queue": "molecular-namd",
        "task": "tools.namd_tool.run_namd",
    },
    "qmmm": {
        "name": "QM/MM",
        "description": "Hybrid quantum mechanics/molecular mechanics via ASH (PySCF + OpenMM)",
        "layer": "multiscale",
        "queue": "qmmm",
        "task": "tools.qmmm_tool.run_qmmm",
    },
    "pybullet": {
        "name": "PyBullet",
        "description": "Rigid body dynamics, collisions, and robotics simulation",
        "layer": "mechanics",
        "queue": "mechanics",
        "task": "tools.pybullet_tool.run_pybullet",
    },
    "einsteinpy": {
        "name": "EinsteinPy",
        "description": "Geodesics and spacetime metrics in general relativity",
        "layer": "relativity",
        "queue": "relativity",
        "task": "tools.einsteinpy_tool.run_einsteinpy",
    },
    "nrpy": {
        "name": "NRPy+",
        "description": "Numerical relativity — BBH initial data, gravitational waves, neutron stars",
        "layer": "relativity",
        "queue": "relativity-nrpy",
        "task": "tools.nrpy_tool.run_nrpy",
    },
    "fenics": {
        "name": "FEniCS",
        "description": "Finite element method — heat, diffusion, Stokes, elasticity",
        "layer": "continuum",
        "queue": "continuum-fenics",
        "task": "tools.fenics_tool.run_fenics",
    },
    "elmer": {
        "name": "Elmer",
        "description": "Multiphysics FEM — structural, thermal, coupled analysis",
        "layer": "continuum",
        "queue": "continuum-elmer",
        "task": "tools.elmer_tool.run_elmer",
    },
    "basico": {
        "name": "BasiCO",
        "description": "Biochemical reaction networks — ODE/stochastic kinetics (COPASI)",
        "layer": "systems-biology",
        "queue": "sysbio",
        "task": "tools.basico_tool.run_basico",
    },
    "tellurium": {
        "name": "Tellurium",
        "description": "SBML/Antimony pathway models — steady-state, MCA",
        "layer": "systems-biology",
        "queue": "sysbio-tel",
        "task": "tools.tellurium_tool.run_tellurium",
    },
    "brian2": {
        "name": "Brian2",
        "description": "Spiking neural networks — LIF, Hodgkin-Huxley, Izhikevich",
        "layer": "neuroscience",
        "queue": "neuro",
        "task": "tools.brian2_tool.run_brian2",
    },
    "nest": {
        "name": "NEST",
        "description": "Large-scale neural simulation — balanced networks, cortical models",
        "layer": "neuroscience",
        "queue": "neuro-nest",
        "task": "tools.nest_tool.run_nest",
    },
    "msprime": {
        "name": "msprime",
        "description": "Coalescent population genetics — demographic models, tree sequences",
        "layer": "evolution",
        "queue": "evolution",
        "task": "tools.msprime_tool.run_msprime",
    },
    "rdkit": {
        "name": "RDKit",
        "description": "Cheminformatics — SMILES parsing, molecular descriptors, fingerprints, 3D conformers",
        "layer": "chemistry",
        "queue": "chemistry",
        "task": "tools.rdkit_tool.run_rdkit",
    },
    "cantera": {
        "name": "Cantera",
        "description": "Chemical kinetics — combustion, ignition delay, flame speed, reactor networks",
        "layer": "chemistry",
        "queue": "kinetics",
        "task": "tools.cantera_tool.run_cantera",
    },
    "qe": {
        "name": "Quantum ESPRESSO",
        "description": "Materials DFT — SCF, band structure, DOS, geometry optimization",
        "layer": "materials",
        "queue": "materials-qe",
        "task": "tools.qe_tool.run_qe",
    },
    "lammps": {
        "name": "LAMMPS",
        "description": "Materials MD — Lennard-Jones fluids, metals, polymer melts",
        "layer": "materials",
        "queue": "materials-lammps",
        "task": "tools.lammps_tool.run_lammps",
    },
    "sympy": {
        "name": "SymPy",
        "description": "Symbolic math — calculus, equation solving, code generation",
        "layer": "mathematics",
        "queue": "symbolic",
        "task": "tools.sympy_tool.run_sympy",
    },
    "gmsh": {
        "name": "Gmsh",
        "description": "Mesh generation — 2D/3D FEM meshes, CAD geometry",
        "layer": "mathematics",
        "queue": "mesh",
        "task": "tools.gmsh_tool.run_gmsh",
    },
    "lcapy": {
        "name": "Lcapy",
        "description": "Symbolic circuits — transfer functions, pole-zero, noise analysis",
        "layer": "circuits",
        "queue": "symbolic-circuits",
        "task": "tools.lcapy_tool.run_lcapy",
    },
    "pennylane": {
        "name": "PennyLane",
        "description": "Differentiable quantum computing — VQE, QNN, gradients",
        "layer": "circuits",
        "queue": "quantum-ml",
        "task": "tools.pennylane_tool.run_pennylane",
    },
    "sagemath": {
        "name": "SageMath",
        "description": "Comprehensive math — algebra, number theory, combinatorics, geometry",
        "layer": "mathematics",
        "queue": "math-sage",
        "task": "tools.sagemath_tool.run_sagemath",
    },
    "lean4": {
        "name": "Lean 4",
        "description": "Formal verification — theorem proving, Mathlib proofs",
        "layer": "mathematics",
        "queue": "math-lean",
        "task": "tools.lean4_tool.run_lean4",
    },
    "gap": {
        "name": "GAP",
        "description": "Group theory — permutation groups, character tables, representations",
        "layer": "mathematics",
        "queue": "math-gap",
        "task": "tools.gap_tool.run_gap",
    },
    "pyspice": {
        "name": "PySpice",
        "description": "Circuit simulation — DC/AC/transient via ngspice backend",
        "layer": "circuits",
        "queue": "circuits-spice",
        "task": "tools.pyspice_tool.run_pyspice",
    },
    "qiskit": {
        "name": "Qiskit",
        "description": "Quantum computing — circuit construction, Aer simulation, VQE",
        "layer": "circuits",
        "queue": "circuits-qiskit",
        "task": "tools.qiskit_tool.run_qiskit",
    },
    "matplotlib": {
        "name": "Matplotlib",
        "description": "Publication-quality static plots — line, scatter, histogram, heatmap, contour, bar",
        "layer": "visualization",
        "queue": "plotting",
        "task": "tools.matplotlib_tool.run_matplotlib",
    },
    "control": {
        "name": "python-control",
        "description": "Control systems — Bode, Nyquist, root locus, step response, state-space",
        "layer": "engineering",
        "queue": "control",
        "task": "tools.control_tool.run_control",
    },
    "pyomo": {
        "name": "Pyomo",
        "description": "LP, MILP, NLP with GLPK/HiGHS/CBC/IPOPT solvers",
        "layer": "engineering",
        "queue": "optimization",
        "task": "tools.pyomo_tool.run_pyomo",
    },
    "networkx": {
        "name": "NetworkX",
        "description": "Graph theory — shortest paths, centrality, community detection, max flow",
        "layer": "engineering",
        "queue": "graph",
        "task": "tools.networkx_tool.run_networkx",
    },
    "phiflow": {
        "name": "PhiFlow",
        "description": "Differentiable physics — smoke, fluid, diffusion, wave (NumPy/JAX backends)",
        "layer": "fluid-dynamics",
        "queue": "diffphys",
        "task": "tools.phiflow_tool.run_phiflow",
    },
    "manim": {
        "name": "Manim",
        "description": "Mathematical animation — equations, functions, geometry, graphs → MP4/GIF",
        "layer": "visualization",
        "queue": "render-manim",
        "task": "tools.manim_tool.run_manim",
    },
    "openfoam": {
        "name": "OpenFOAM",
        "description": "CFD — lid-driven cavity, pipe flow, external flow with icoFoam/simpleFoam",
        "layer": "fluid-dynamics",
        "queue": "cfd-foam",
        "task": "tools.openfoam_tool.run_openfoam",
    },
    "dedalus": {
        "name": "Dedalus",
        "description": "Spectral PDE solver — Rayleigh-Bénard convection, diffusion, waves",
        "layer": "fluid-dynamics",
        "queue": "spectral-pde",
        "task": "tools.dedalus_tool.run_dedalus",
    },
    "su2": {
        "name": "SU2",
        "description": "Compressible CFD — Euler, RANS, transonic/supersonic airfoil flow",
        "layer": "fluid-dynamics",
        "queue": "cfd-su2",
        "task": "tools.su2_tool.run_su2",
    },
    "firedrake": {
        "name": "Firedrake",
        "description": "Finite element method — Poisson, Stokes, elasticity, advection-diffusion (PETSc)",
        "layer": "continuum",
        "queue": "continuum-firedrake",
        "task": "tools.firedrake_tool.run_firedrake",
    },
    "vtk": {
        "name": "VTK",
        "description": "Scientific visualization — field render, isosurface, streamlines, volume render",
        "layer": "visualization",
        "queue": "rendering",
        "task": "tools.vtk_tool.run_vtk",
    },
    "openbabel": {
        "name": "Open Babel",
        "description": "Universal chemical format converter — 110+ formats, 3D optimization, protonation",
        "layer": "chemistry",
        "queue": "cheminformatics",
        "task": "tools.openbabel_tool.run_openbabel",
    },
    "comsol": {
        "name": "COMSOL",
        "description": "Multiphysics FEM (DEFERRED — license required). Use FEniCS/Elmer/Firedrake.",
        "layer": "continuum",
        "queue": "continuum-comsol",
        "task": "tools.comsol_stub.run_comsol",
        "deferred": True,
    },
    "alphafold": {
        "name": "AlphaFold",
        "description": "Protein structure prediction (DEFERRED — ~500GB storage required). Use PyRosetta/OpenMM.",
        "layer": "bio-structure",
        "queue": "bio-alphafold",
        "task": "tools.alphafold_stub.run_alphafold",
        "deferred": True,
    },
    "slim": {
        "name": "SLiM",
        "description": "Forward-time evolutionary simulation — neutral, selection, nucleotide, spatial models",
        "layer": "evolution",
        "queue": "evolution-slim",
        "task": "tools.slim_tool.run_slim",
    },
    "tskit": {
        "name": "tskit",
        "description": "Tree sequence analysis — diversity, Fst, recapitation (post-hoc analysis of SLiM/msprime)",
        "layer": "evolution",
        "queue": "evolution-tskit",
        "task": "tools.tskit_tool.run_tskit",
    },
    "simupop": {
        "name": "simuPOP",
        "description": "Forward-time population genetics — random mating, island migration, selection+drift",
        "layer": "evolution",
        "queue": "evolution-simupop",
        "task": "tools.simupop_tool.run_simupop",
    },
    "pyrosetta": {
        "name": "PyRosetta",
        "description": "Protein modeling and design (DEFERRED — academic license required). Use OpenMM.",
        "layer": "bio-structure",
        "queue": "bio-pyrosetta",
        "task": "tools.pyrosetta_stub.run_pyrosetta",
        "deferred": True,
    },
    "einstein_toolkit": {
        "name": "Einstein Toolkit",
        "description": "Full numerical relativity — BBH inspiral, neutron stars, dynamical spacetimes (Cactus/McLachlan)",
        "layer": "relativity",
        "queue": "astro-etk",
        "task": "tools.etk_tool.run_etk",
    },
    "rayoptics": {
        "name": "RayOptics",
        "description": "Geometrical ray tracing — singlet/doublet lenses, spot diagrams",
        "layer": "optics",
        "queue": "optics-ray",
        "task": "tools.rayoptics_tool.run_rayoptics",
    },
    "lightpipes": {
        "name": "LightPipes",
        "description": "Physical wave optics — diffraction, interference, beam propagation",
        "layer": "optics",
        "queue": "optics-wave",
        "task": "tools.lightpipes_tool.run_lightpipes",
    },
    "strawberryfields": {
        "name": "Strawberry Fields",
        "description": "Quantum photonics — squeezed states, HOM effect, boson sampling, Gaussian circuits",
        "layer": "optics",
        "queue": "optics-quantum",
        "task": "tools.strawberryfields_tool.run_strawberryfields",
    },
    "meep": {
        "name": "Meep",
        "description": "FDTD electromagnetic simulation — waveguides, resonators, photonic crystals",
        "layer": "optics",
        "queue": "em-meep",
        "task": "tools.meep_tool.run_meep",
    },
}

# Layer definitions
LAYERS = {
    "astrophysics": {
        "name": "Astrophysics",
        "description": "Celestial mechanics and gravitational N-body simulations",
        "tools": ["rebound"],
    },
    "quantum": {
        "name": "Quantum Mechanics",
        "description": "Quantum state evolution, open quantum systems",
        "tools": ["qutip"],
    },
    "molecular": {
        "name": "Molecular Dynamics",
        "description": "Atomistic and coarse-grained molecular simulations",
        "tools": ["openmm", "gromacs", "namd"],
    },
    "electronic": {
        "name": "Electronic Structure",
        "description": "Ab initio quantum chemistry and electronic structure methods",
        "tools": ["pyscf", "psi4"],
    },
    "analysis": {
        "name": "Analysis",
        "description": "Post-processing, trajectory analysis, and data reduction",
        "tools": ["mdanalysis"],
    },
    "multiscale": {
        "name": "Multiscale",
        "description": "Coupled multi-scale simulation methods",
        "tools": ["qmmm"],
    },
    "mechanics": {
        "name": "Classical Mechanics",
        "description": "Rigid body dynamics, collisions, and classical physics",
        "tools": ["pybullet"],
    },
    "continuum": {
        "name": "Continuum Mechanics",
        "description": "Finite element methods for PDEs, structural, and thermal analysis",
        "tools": ["fenics", "elmer", "firedrake", "comsol"],
    },
    "relativity": {
        "name": "General Relativity",
        "description": "Geodesics, spacetime metrics, gravitational waves, and numerical relativity",
        "tools": ["einsteinpy", "nrpy", "einstein_toolkit"],
    },
    "systems-biology": {
        "name": "Systems Biology",
        "description": "Biochemical reaction networks, pathway modeling, and metabolic control",
        "tools": ["basico", "tellurium"],
    },
    "neuroscience": {
        "name": "Neuroscience",
        "description": "Spiking neural networks and large-scale brain circuit simulation",
        "tools": ["brian2", "nest"],
    },
    "evolution": {
        "name": "Evolution",
        "description": "Population genetics, coalescent theory, forward-time simulation, and tree sequence analysis",
        "tools": ["msprime", "slim", "tskit", "simupop"],
    },
    "chemistry": {
        "name": "Chemistry",
        "description": "Cheminformatics, molecular properties, chemical kinetics, and format conversion",
        "tools": ["rdkit", "cantera", "openbabel"],
    },
    "materials": {
        "name": "Materials",
        "description": "Materials science DFT, molecular dynamics, and solid-state simulations",
        "tools": ["qe", "lammps"],
    },
    "mathematics": {
        "name": "Mathematics",
        "description": "Symbolic math, mesh generation, formal verification, and group theory",
        "tools": ["sympy", "gmsh", "sagemath", "lean4", "gap"],
    },
    "circuits": {
        "name": "Circuits",
        "description": "Circuit simulation, symbolic circuit analysis, and quantum computing",
        "tools": ["lcapy", "pyspice", "qiskit", "pennylane"],
    },
    "visualization": {
        "name": "Visualization",
        "description": "Publication-quality plots and mathematical animation rendering",
        "tools": ["matplotlib", "manim", "vtk"],
    },
    "fluid-dynamics": {
        "name": "Fluid Dynamics",
        "description": "CFD, spectral PDE solvers, and differentiable fluid simulation",
        "tools": ["openfoam", "dedalus", "phiflow", "su2"],
    },
    "engineering": {
        "name": "Engineering",
        "description": "Control systems, mathematical optimization, and graph theory",
        "tools": ["control", "pyomo", "networkx"],
    },
    "bio-structure": {
        "name": "Biological Structure",
        "description": "Protein structure prediction, modeling, and design",
        "tools": ["alphafold", "pyrosetta"],
    },
    "optics": {
        "name": "Optics & Photonics",
        "description": "Ray tracing, wave optics, quantum photonics, and electromagnetic FDTD simulation",
        "tools": ["rayoptics", "lightpipes", "strawberryfields", "meep"],
    },
}

# Presets — quick-launch configurations
PRESETS = {
    "inner_solar_system": {
        "tool": "rebound",
        "label": "Inner Solar System",
        "description": "Mercury–Mars orbiting the Sun for 10 years",
        "example_file": "rebound_solar_system.json",
    },
    "rabi_oscillation": {
        "tool": "qutip",
        "label": "Rabi Oscillation",
        "description": "Two-level atom driven by resonant field",
        "example_file": "qutip_rabi.json",
    },
    "alanine_dipeptide": {
        "tool": "openmm",
        "label": "Alanine Dipeptide",
        "description": "Small peptide MD in vacuum",
        "example_file": "openmm_alanine.json",
    },
    "h2_hartree_fock": {
        "tool": "pyscf",
        "label": "H₂ Hartree-Fock",
        "description": "Hydrogen molecule HF/STO-3G electronic structure",
        "example_file": "pyscf_h2.json",
    },
    "qmmm_alanine": {
        "tool": "qmmm",
        "label": "QM/MM Alanine",
        "description": "Alanine dipeptide with QM active site + MM surroundings",
        "example_file": "qmmm_enzyme_active_site.json",
    },
    "pybullet_collision": {
        "tool": "pybullet",
        "label": "Elastic Collision",
        "description": "Two-sphere elastic collision with energy conservation",
        "example_file": "pybullet_collision.json",
    },
    "schwarzschild_orbit": {
        "tool": "einsteinpy",
        "label": "Schwarzschild Orbit",
        "description": "Stable geodesic orbit around a Schwarzschild black hole",
        "example_file": "einsteinpy_schwarzschild.json",
    },
    "bbh_merger": {
        "tool": "nrpy",
        "label": "BBH Merger",
        "description": "Equal-mass binary black hole gravitational wave strain",
        "example_file": "nrpy_bbh_merger.json",
    },
    "heated_plate": {
        "tool": "fenics",
        "label": "Heated Plate",
        "description": "Steady-state heat conduction on a square plate",
        "example_file": "fenics_heat_plate.json",
    },
    "cantilever_beam": {
        "tool": "elmer",
        "label": "Cantilever Beam",
        "description": "Cantilever beam deflection under gravity",
        "example_file": "elmer_cantilever.json",
    },
    "enzyme_kinetics": {
        "tool": "basico",
        "label": "Enzyme Kinetics",
        "description": "Michaelis-Menten enzyme-substrate reaction network",
        "example_file": "basico_enzyme.json",
    },
    "linear_pathway": {
        "tool": "tellurium",
        "label": "Linear Pathway",
        "description": "Three-step linear metabolic pathway S1→S2→S3",
        "example_file": "tellurium_pathway.json",
    },
    "lif_network": {
        "tool": "brian2",
        "label": "LIF Network",
        "description": "100-neuron leaky integrate-and-fire with Poisson input",
        "example_file": "brian2_lif.json",
    },
    "brunel_network": {
        "tool": "nest",
        "label": "Brunel Network",
        "description": "Brunel 2000 balanced excitatory-inhibitory network",
        "example_file": "nest_brunel.json",
    },
    "neutral_coalescent": {
        "tool": "msprime",
        "label": "Neutral Coalescent",
        "description": "50-sample coalescent with neutral mutations on 100kb",
        "example_file": "msprime_coalescent.json",
    },
    "aspirin_descriptors": {
        "tool": "rdkit",
        "label": "Aspirin Descriptors",
        "description": "Aspirin molecular descriptors and properties via RDKit",
        "example_file": "rdkit_aspirin.json",
    },
    "hydrogen_ignition": {
        "tool": "cantera",
        "label": "H₂/Air Ignition",
        "description": "Hydrogen/air ignition delay at 1200 K",
        "example_file": "cantera_h2_ignition.json",
    },
    "silicon_scf": {
        "tool": "qe",
        "label": "Silicon SCF",
        "description": "Silicon crystal self-consistent field DFT calculation",
        "example_file": "qe_silicon.json",
    },
    "lj_fluid": {
        "tool": "lammps",
        "label": "LJ Fluid",
        "description": "Lennard-Jones fluid molecular dynamics simulation",
        "example_file": "lammps_lj.json",
    },
    "quadratic_solve": {
        "tool": "sympy",
        "label": "Quadratic Solve",
        "description": "Solve a quadratic equation symbolically with SymPy",
        "example_file": "sympy_quadratic.json",
    },
    "box_mesh_3d": {
        "tool": "gmsh",
        "label": "3D Box Mesh",
        "description": "Generate a 3D box mesh with Gmsh",
        "example_file": "gmsh_box.json",
    },
    "rc_lowpass": {
        "tool": "lcapy",
        "label": "RC Low-Pass Filter",
        "description": "Symbolic RC low-pass filter transfer function",
        "example_file": "lcapy_rc.json",
    },
    "h2_vqe": {
        "tool": "pennylane",
        "label": "H\u2082 VQE",
        "description": "Variational Quantum Eigensolver for H\u2082 molecule",
        "example_file": "pennylane_h2_vqe.json",
    },
    "polynomial_groebner": {
        "tool": "sagemath",
        "label": "Gr\u00f6bner Basis",
        "description": "Compute Gr\u00f6bner basis of polynomial ideal with SageMath",
        "example_file": "sagemath_groebner.json",
    },
    "nat_add_comm": {
        "tool": "lean4",
        "label": "Nat Addition Commutative",
        "description": "Verify commutativity of natural number addition in Lean 4",
        "example_file": "lean4_nat_comm.json",
    },
    "symmetric_group": {
        "tool": "gap",
        "label": "Symmetric Group S5",
        "description": "Conjugacy classes of symmetric group S\u2085 in GAP",
        "example_file": "gap_symmetric.json",
    },
    "rlc_transient": {
        "tool": "pyspice",
        "label": "RLC Transient",
        "description": "RLC circuit transient analysis with PySpice/ngspice",
        "example_file": "pyspice_rlc.json",
    },
    "bell_state": {
        "tool": "qiskit",
        "label": "Bell State",
        "description": "Create and measure a Bell state with Qiskit",
        "example_file": "qiskit_bell.json",
    },
    "sine_plot": {
        "tool": "matplotlib",
        "label": "Sine Wave Plot",
        "description": "Publication-quality sine wave plot with Matplotlib",
        "example_file": "matplotlib_sine.json",
    },
    "rc_bode": {
        "tool": "control",
        "label": "RC Low-Pass Bode",
        "description": "Bode plot of an RC low-pass filter transfer function",
        "example_file": "control_rc_bode.json",
    },
    "knapsack_lp": {
        "tool": "pyomo",
        "label": "Knapsack Problem",
        "description": "Binary knapsack optimization with Pyomo + GLPK",
        "example_file": "pyomo_knapsack.json",
    },
    "karate_club": {
        "tool": "networkx",
        "label": "Karate Club Graph",
        "description": "Community detection on Zachary's karate club network",
        "example_file": "networkx_karate.json",
    },
    "smoke_plume": {
        "tool": "phiflow",
        "label": "Smoke Plume",
        "description": "Buoyant smoke plume simulation with PhiFlow",
        "example_file": "phiflow_smoke.json",
    },
    "pythagorean_anim": {
        "tool": "manim",
        "label": "Pythagorean Theorem",
        "description": "Animated equation transformation with Manim",
        "example_file": "manim_pythagorean.json",
    },
    "lid_cavity": {
        "tool": "openfoam",
        "label": "Lid-Driven Cavity",
        "description": "Classic lid-driven cavity flow with OpenFOAM",
        "example_file": "openfoam_cavity.json",
    },
    "rayleigh_benard": {
        "tool": "dedalus",
        "label": "Rayleigh-Bénard Convection",
        "description": "Thermal convection with Dedalus spectral solver",
        "example_file": "dedalus_rb.json",
    },
    "naca_airfoil": {
        "tool": "su2",
        "label": "NACA 0012 Airfoil",
        "description": "NACA 0012 inviscid transonic airfoil at Mach 0.8",
        "example_file": "su2_naca_airfoil.json",
    },
    "firedrake_poisson": {
        "tool": "firedrake",
        "label": "Firedrake Poisson",
        "description": "Poisson equation on unit square with zero BCs",
        "example_file": "firedrake_poisson.json",
    },
    "qutip_bloch_anim": {
        "tool": "manim",
        "label": "Bloch Sphere Animation",
        "description": "Animated Bloch sphere trajectory from Rabi oscillation",
        "example_file": "manim_bloch.json",
    },
    "vtk_isosurface": {
        "tool": "vtk",
        "label": "VTK Field Render",
        "description": "VTK server-side field visualization with colormap",
        "example_file": "vtk_isosurface.json",
    },
    "knapsack_highs": {
        "tool": "pyomo",
        "label": "Knapsack (HiGHS)",
        "description": "Binary knapsack optimization with Pyomo + HiGHS solver",
        "example_file": "pyomo_knapsack.json",
    },
    "aspirin_smi_to_sdf": {
        "tool": "openbabel",
        "label": "Aspirin SMILES → SDF",
        "description": "Convert aspirin SMILES to 3D SDF format with Open Babel",
        "example_file": "openbabel_aspirin_convert.json",
    },
    "mercury_precession_gr": {
        "tool": "rebound",
        "label": "Mercury GR Precession",
        "description": "Mercury perihelion precession with REBOUNDx GR corrections (42.98\"/century)",
        "example_file": "rebound_mercury_gr.json",
    },
    "slim_neutral_evolution": {
        "tool": "slim",
        "label": "SLiM Neutral Evolution",
        "description": "Wright-Fisher neutral evolution (N=500, 1000 gens, 100kb) with tree sequence output",
        "example_file": "slim_neutral.json",
    },
    "tskit_diversity_analysis": {
        "tool": "tskit",
        "label": "tskit Diversity",
        "description": "Windowed nucleotide diversity and Tajima's D from a tree sequence",
        "example_file": "tskit_diversity.json",
    },
    "simupop_island_migration": {
        "tool": "simupop",
        "label": "simuPOP Island Migration",
        "description": "3-population island model with migration (m=0.01)",
        "example_file": "simupop_migration.json",
    },
    "simupop_random_mating": {
        "tool": "simupop",
        "label": "simuPOP Random Mating",
        "description": "Wright-Fisher random mating with allele frequency tracking",
        "example_file": "simupop_random_mating.json",
    },
    "etk_bbh_inspiral": {
        "tool": "einstein_toolkit",
        "label": "ETK BBH Inspiral",
        "description": "Equal-mass binary black hole inspiral with Cactus/McLachlan (low resolution)",
        "example_file": "etk_bbh.json",
    },
    "rayoptics_singlet": {
        "tool": "rayoptics",
        "label": "Biconvex Singlet Lens",
        "description": "Biconvex singlet lens ray trace with spot diagram (100mm f/5)",
        "example_file": "rayoptics_singlet.json",
    },
    "lightpipes_double_slit": {
        "tool": "lightpipes",
        "label": "Young's Double Slit",
        "description": "Young's double-slit experiment at 532nm, 0.2mm separation, 1m propagation",
        "example_file": "lightpipes_double_slit.json",
    },
    "strawberryfields_hom": {
        "tool": "strawberryfields",
        "label": "Hong-Ou-Mandel Effect",
        "description": "Hong-Ou-Mandel two-photon interference on a 50:50 beam splitter",
        "example_file": "strawberryfields_hom.json",
    },
    "meep_waveguide": {
        "tool": "meep",
        "label": "Waveguide Bend",
        "description": "Dielectric waveguide 90° bend at 1.55µm with FDTD field visualization",
        "example_file": "meep_waveguide.json",
    },
    # --- Optics additional simulation-type presets ---
    "rayoptics_doublet": {
        "tool": "rayoptics",
        "label": "Achromatic Doublet Lens",
        "description": "Crown-flint achromatic doublet (200mm f/8, N-BK7 + N-SF2) with chromatic ray trace",
        "example_file": "rayoptics_doublet.json",
    },
    "rayoptics_spot": {
        "tool": "rayoptics",
        "label": "Spot Diagram — f/4 Singlet",
        "description": "Spot diagram of an f/4 singlet lens showing ray intersection pattern at image plane",
        "example_file": "rayoptics_spot.json",
    },
    "lightpipes_circular": {
        "tool": "lightpipes",
        "label": "Airy Disk — Circular Aperture",
        "description": "Fraunhofer diffraction through a circular aperture (632.8nm HeNe, 0.5mm radius)",
        "example_file": "lightpipes_circular.json",
    },
    "lightpipes_lens": {
        "tool": "lightpipes",
        "label": "Gaussian Beam Lens Focus",
        "description": "Gaussian beam focused by a thin lens (532nm, f=500mm, 2mm beam radius)",
        "example_file": "lightpipes_lens.json",
    },
    "lightpipes_interferometer": {
        "tool": "lightpipes",
        "label": "Mach-Zehnder Interferometer",
        "description": "Mach-Zehnder interferometer with tilted mirror arm (632.8nm HeNe)",
        "example_file": "lightpipes_interferometer.json",
    },
    "strawberryfields_squeezed": {
        "tool": "strawberryfields",
        "label": "Squeezed Vacuum State",
        "description": "Single-mode squeezed vacuum (r=0.7) with photon number distribution",
        "example_file": "strawberryfields_squeezed.json",
    },
    "strawberryfields_boson": {
        "tool": "strawberryfields",
        "label": "4-Mode Boson Sampling",
        "description": "Boson sampling through a random 4-mode interferometer with 2 input photons",
        "example_file": "strawberryfields_boson.json",
    },
    "strawberryfields_gaussian": {
        "tool": "strawberryfields",
        "label": "Two-Mode Gaussian State",
        "description": "Squeezed-displaced two-mode Gaussian state with Wigner function visualization",
        "example_file": "strawberryfields_gaussian.json",
    },
    "meep_ring": {
        "tool": "meep",
        "label": "Ring Resonator",
        "description": "Microring resonator coupled to bus waveguide at 1.55µm (R=5µm, gap=0.1µm)",
        "example_file": "meep_ring.json",
    },
    "meep_photonic_crystal": {
        "tool": "meep",
        "label": "2D Photonic Crystal",
        "description": "7×7 square-lattice rod array photonic crystal with FDTD field map",
        "example_file": "meep_photonic_crystal.json",
    },
    "meep_dipole": {
        "tool": "meep",
        "label": "Point Dipole Radiation",
        "description": "Point dipole source radiation pattern in free space",
        "example_file": "meep_dipole.json",
    },
}

# Named Pipelines — predefined multi-step configurations
PIPELINES = {
    "quantum_to_organism": {
        "label": "Quantum-to-Organism",
        "description": "Full scale traverse: quantum mechanics → electronic structure → molecular dynamics → analysis → systems biology → population genetics",
        "steps": [
            {"tool": "qutip", "params": {"system_type": "qubit_rabi", "qubit_rabi": {"omega": 1.0, "delta": 0.0, "psi0": "ground", "tmax": 25.0}}, "label": "Quantum dynamics"},
            {"tool": "pyscf", "params": {"method": "hf", "basis": "sto-3g", "atom_coords": "H 0 0 0; H 0 0 0.74"}, "param_map": {}, "label": "Electronic structure"},
            {"tool": "openmm", "params": {"integrator": "langevin", "temperature": 300, "steps": 5000, "report_interval": 50}, "param_map": {"pdb_content": "$prev.result.pdb_block"}, "label": "Molecular dynamics"},
            {"tool": "mdanalysis", "params": {"analysis_type": "rmsd"}, "param_map": {"source_job_id": "$prev.job_id"}, "label": "Trajectory analysis"},
            {"tool": "basico", "params": {"model_type": "enzyme_kinetics"}, "label": "Pathway modeling"},
            {"tool": "slim", "params": {"simulation_type": "neutral_evolution", "population_size": 500, "n_generations": 100, "sequence_length": 10000}, "label": "Population evolution"},
            {"tool": "tskit", "params": {"simulation_type": "diversity"}, "param_map": {"source_job_id": "$prev.job_id"}, "label": "Tree sequence analysis"},
        ],
    },
    "mercury_precession": {
        "label": "Mercury GR Precession",
        "description": "Mercury perihelion precession with REBOUNDx GR corrections (42.98\"/century)",
        "steps": [
            {"tool": "rebound", "params": {"gr_correction": "gr_full", "integrator": "ias15", "tmax": 62.83, "n_outputs": 500}, "label": "N-body with GR"},
        ],
    },
    "qmmm_enzyme": {
        "label": "QM/MM Enzyme Catalysis",
        "description": "Drug binding: ligand identification → QM/MM active site → trajectory analysis → pathway kinetics",
        "steps": [
            {"tool": "rdkit", "params": {"simulation_type": "descriptors", "smiles": "CC(=O)Oc1ccccc1C(=O)O"}, "label": "Ligand preparation"},
            {"tool": "qmmm", "params": {"qm_method": "hf", "qm_basis": "sto-3g"}, "param_map": {"ligand_data": "$prev.result"}, "label": "QM/MM simulation"},
            {"tool": "mdanalysis", "params": {"analysis_type": "rmsd"}, "param_map": {"source_job_id": "$prev.job_id"}, "label": "Trajectory analysis"},
            {"tool": "basico", "params": {"model_type": "enzyme_kinetics"}, "label": "Kinetic modeling"},
        ],
    },
    "evolution_structure": {
        "label": "Evolution → Structure Feedback",
        "description": "Watch proteins evolve: coalescent → forward sim → tree analysis → structure prediction → MD refinement",
        "steps": [
            {"tool": "msprime", "params": {"simulation_type": "coalescent", "sample_size": 50, "sequence_length": 100000, "recombination_rate": 1e-8, "mutation_rate": 1e-8}, "label": "Coalescent history"},
            {"tool": "slim", "params": {"simulation_type": "nucleotide_evolution", "population_size": 500, "n_generations": 200, "sequence_length": 10000}, "label": "Forward evolution"},
            {"tool": "tskit", "params": {"simulation_type": "diversity"}, "param_map": {"source_job_id": "$prev.job_id"}, "label": "Diversity analysis"},
        ],
    },
    "multiscale_tissue": {
        "label": "Multiscale Tissue Modeling",
        "description": "FEniCS tissue stress → COPASI biochemical response (bidirectional multiscale)",
        "steps": [
            {"tool": "fenics", "params": {"simulation_type": "elasticity"}, "label": "Tissue mechanics"},
            {"tool": "basico", "params": {"model_type": "enzyme_kinetics"}, "param_map": {"diffusion_field": "$prev.result.field_data"}, "label": "Biochemical response"},
        ],
    },
    "drug_discovery": {
        "label": "Drug Discovery",
        "description": "SMILES → quantum properties → MD binding → trajectory analysis → pathway impact",
        "steps": [
            {"tool": "rdkit", "params": {"simulation_type": "descriptors", "smiles": "CC(=O)Oc1ccccc1C(=O)O"}, "label": "Molecular properties"},
            {"tool": "pyscf", "params": {"method": "hf", "basis": "sto-3g"}, "param_map": {"atom_coords": "$prev.result.atom_coords_pyscf"}, "label": "Quantum chemistry"},
            {"tool": "openmm", "params": {"integrator": "langevin", "temperature": 300, "steps": 5000, "report_interval": 50}, "param_map": {"pdb_content": "$prev.result.pdb_block"}, "label": "MD simulation"},
            {"tool": "mdanalysis", "params": {"analysis_type": "rmsd"}, "param_map": {"source_job_id": "$prev.job_id"}, "label": "Binding analysis"},
            {"tool": "basico", "params": {"model_type": "enzyme_kinetics"}, "label": "Pathway modeling"},
        ],
    },
    "materials_discovery": {
        "label": "Materials Discovery",
        "description": "DFT properties → large-scale MD → trajectory analysis → continuum simulation",
        "steps": [
            {"tool": "qe", "params": {"simulation_type": "scf"}, "label": "DFT calculation"},
            {"tool": "lammps", "params": {"simulation_type": "lj_fluid"}, "param_map": {"potential_data": "$prev.result"}, "label": "MD simulation"},
            {"tool": "mdanalysis", "params": {"analysis_type": "rmsd"}, "param_map": {"source_job_id": "$prev.result.trajectory_job_id"}, "label": "Trajectory analysis"},
            {"tool": "fenics", "params": {"simulation_type": "heat"}, "label": "Continuum simulation"},
        ],
    },
    "reactive_multiphysics": {
        "label": "Reactive Multiphysics",
        "description": "Symbolic rate expressions → detailed kinetics → reactive transport PDE on generated mesh",
        "steps": [
            {"tool": "sympy", "params": {"simulation_type": "solve", "expression": "k*A - k_r*B", "variable": "A"}, "label": "Symbolic rates"},
            {"tool": "cantera", "params": {"simulation_type": "ignition_delay"}, "param_map": {"rate_expression": "$prev.result.expression"}, "label": "Detailed kinetics"},
            {"tool": "gmsh", "params": {"mesh_type": "box_3d"}, "label": "Mesh generation"},
            {"tool": "fenics", "params": {"simulation_type": "heat"}, "param_map": {"mesh_file": "$prev.result.mesh_file_path"}, "label": "Reactive transport"},
        ],
    },
    "math_verification": {
        "label": "Mathematics Verification Loop",
        "description": "Symbolic computation → algebraic enrichment → formal proof verification",
        "steps": [
            {"tool": "sympy", "params": {"simulation_type": "solve", "expression": "x**2 - 2", "variable": "x"}, "label": "Symbolic computation"},
            {"tool": "sagemath", "params": {"simulation_type": "groebner_basis"}, "param_map": {"polynomials": "$prev.result.result"}, "label": "Algebraic analysis"},
            {"tool": "lean4", "params": {"simulation_type": "verify"}, "label": "Formal verification"},
        ],
    },
    "classical_circuit": {
        "label": "Classical Circuit Design",
        "description": "Symbolic analysis → numerical SPICE simulation → EM field verification",
        "steps": [
            {"tool": "lcapy", "params": {"simulation_type": "transfer_function"}, "label": "Symbolic circuit"},
            {"tool": "pyspice", "params": {"simulation_type": "transient"}, "param_map": {"netlist": "$prev.result.spice_netlist"}, "label": "SPICE simulation"},
            {"tool": "fenics", "params": {"simulation_type": "heat"}, "label": "EM field verification"},
        ],
    },
    "quantum_chemistry_qc": {
        "label": "QC on Quantum Computers",
        "description": "Molecular structure → Hamiltonian → qubit mapping → variational quantum optimization",
        "steps": [
            {"tool": "rdkit", "params": {"simulation_type": "descriptors", "smiles": "O"}, "label": "Molecular structure"},
            {"tool": "pyscf", "params": {"method": "hf", "basis": "sto-3g"}, "param_map": {"atom_coords": "$prev.result.atom_coords_pyscf"}, "label": "Hamiltonian"},
            {"tool": "qiskit", "params": {"simulation_type": "vqe"}, "param_map": {"atom_coords": "$prev.result.molecular_geometry"}, "label": "VQE (Qiskit)"},
            {"tool": "pennylane", "params": {"simulation_type": "vqe"}, "label": "Optimization (PennyLane)"},
        ],
    },
    "photonic_design": {
        "label": "Photonic Device Design",
        "description": "End-to-end photonic design: ray optics lens layout → wave propagation → FDTD verification → publication plot",
        "steps": [
            {"tool": "rayoptics", "params": {"simulation_type": "singlet_lens", "singlet_lens": {"efl": 100.0, "f_number": 5.0}}, "label": "Lens layout (ray optics)"},
            {"tool": "lightpipes", "params": {"simulation_type": "lens_focus", "lens_focus": {"focal_length": 0.1, "beam_radius": 2e-3}}, "param_map": {"lens_focus.focal_length": "$prev.result.efl"}, "label": "Wave propagation"},
            {"tool": "meep", "params": {"simulation_type": "waveguide_bend"}, "label": "FDTD verification"},
            {"tool": "matplotlib", "params": {"plot_type": "heatmap"}, "param_map": {"z_data": "$prev.result.field_ez"}, "label": "Publication plot"},
        ],
    },
}

# Couplings registry — defines allowed tool connections
COUPLINGS = {
    "openmm_to_mdanalysis": {
        "from": "openmm",
        "to": "mdanalysis",
        "type": "sequential",
        "description": "Analyze OpenMM trajectory with MDAnalysis",
        "default_param_map": {"source_job_id": "$prev.job_id"},
    },
    "gromacs_to_mdanalysis": {
        "from": "gromacs",
        "to": "mdanalysis",
        "type": "sequential",
        "description": "Analyze GROMACS trajectory with MDAnalysis",
        "default_param_map": {"source_job_id": "$prev.job_id"},
    },
    "namd_to_mdanalysis": {
        "from": "namd",
        "to": "mdanalysis",
        "type": "sequential",
        "description": "Analyze NAMD trajectory with MDAnalysis",
        "default_param_map": {"source_job_id": "$prev.job_id"},
    },
    "qutip_to_pyscf": {
        "from": "qutip",
        "to": "pyscf",
        "type": "sequential",
        "description": "Use QuTiP state to initialize PySCF electronic structure",
        "default_param_map": {},
    },
    "qmmm_concurrent": {
        "from": "pyscf",
        "to": "openmm",
        "type": "concurrent",
        "description": "QM/MM: PySCF active site + OpenMM surroundings via ASH",
        "tool": "qmmm",
    },
    "fenics_to_elmer": {
        "from": "fenics",
        "to": "elmer",
        "type": "sequential",
        "description": "FEniCS thermal solution → Elmer structural analysis (thermal-structural coupling)",
        "default_param_map": {"temperature_field": "$prev.result.field_data"},
    },
    "pybullet_to_fenics": {
        "from": "pybullet",
        "to": "fenics",
        "type": "sequential",
        "description": "PyBullet contact forces → FEniCS stress analysis",
        "default_param_map": {"source_forces": "$prev.result.collisions"},
    },
    "tellurium_to_copasi": {
        "from": "tellurium",
        "to": "basico",
        "type": "sequential",
        "description": "Tellurium SBML export → BasiCO parameter estimation/sensitivity",
        "default_param_map": {"sbml_string": "$prev.result.sbml_export", "model_source": "sbml"},
    },
    "copasi_to_brian2": {
        "from": "basico",
        "to": "brian2",
        "type": "sequential",
        "description": "COPASI concentration time-series → Brian2 input current (milestone coupling)",
        "default_param_map": {"input_current_timeseries": "$prev.result"},
    },
    "rdkit_to_pyscf": {
        "from": "rdkit",
        "to": "pyscf",
        "type": "sequential",
        "description": "RDKit SMILES → 3D conformer → PySCF electronic structure (milestone coupling)",
        "default_param_map": {"atom_coords": "$prev.result.atom_coords_pyscf"},
    },
    "lammps_to_mdanalysis": {
        "from": "lammps",
        "to": "mdanalysis",
        "type": "sequential",
        "description": "LAMMPS trajectory → MDAnalysis post-processing",
        "default_param_map": {"source_job_id": "$prev.result.trajectory_job_id"},
    },
    "sympy_to_fenics": {
        "from": "sympy",
        "to": "fenics",
        "type": "sequential",
        "description": "SymPy symbolic PDE → FEniCS UFL weak form (code generation)",
        "default_param_map": {"ufl_code": "$prev.result.ufl_code", "symbolic_source": "$prev.result.expression"},
    },
    "gmsh_to_fenics": {
        "from": "gmsh",
        "to": "fenics",
        "type": "sequential",
        "description": "Gmsh mesh (.msh) → FEniCS dolfinx mesh import",
        "default_param_map": {"mesh_file": "$prev.result.mesh_file_path"},
    },
    "lcapy_to_pyspice": {
        "from": "lcapy",
        "to": "pyspice",
        "type": "sequential",
        "description": "Symbolic circuit design → numerical SPICE simulation",
        "default_param_map": {"netlist": "$prev.result.spice_netlist"},
    },
    "qiskit_to_qutip": {
        "from": "qiskit",
        "to": "qutip",
        "type": "sequential",
        "description": "Qiskit OpenQASM export → QuTiP-QIP circuit import",
        "default_param_map": {"qasm_str": "$prev.result.qasm_str"},
    },
    "qiskit_to_pyscf": {
        "from": "qiskit",
        "to": "pyscf",
        "type": "sequential",
        "description": "Qiskit Nature → molecular VQE Hamiltonian",
        "default_param_map": {"atom_coords": "$prev.result.molecular_geometry"},
    },
    "pennylane_to_qiskit": {
        "from": "pennylane",
        "to": "qiskit",
        "type": "sequential",
        "description": "PennyLane qiskit.aer device plugin → Qiskit backend execution",
        "default_param_map": {"gates": "$prev.result.gate_sequence", "n_qubits": "$prev.result.n_qubits"},
    },
    "gmsh_to_openfoam": {
        "from": "gmsh",
        "to": "openfoam",
        "type": "sequential",
        "description": "Gmsh mesh (.msh) → OpenFOAM mesh (via gmshToFoam utility)",
        "default_param_map": {"mesh_file": "$prev.result.mesh_file_path"},
    },
    "sympy_to_manim": {
        "from": "sympy",
        "to": "manim",
        "type": "sequential",
        "description": "SymPy expression/equation → Manim animated math visualization",
        "default_param_map": {"expressions": "$prev.result.latex"},
    },
    "sympy_to_pyomo": {
        "from": "sympy",
        "to": "pyomo",
        "type": "sequential",
        "description": "Symbolic expressions → Pyomo optimization model constraints/objective",
        "default_param_map": {"objective": {"expression": "$prev.result.expression"}},
    },
    "rebound_to_manim": {
        "from": "rebound",
        "to": "manim",
        "type": "sequential",
        "description": "REBOUND particle trajectories → animated orbital visualization",
        "default_param_map": {"trajectories": "$prev.result.trajectories"},
    },
    "fenics_to_matplotlib": {
        "from": "fenics",
        "to": "matplotlib",
        "type": "sequential",
        "description": "FEniCS solution fields → publication-quality Matplotlib plot",
        "default_param_map": {"z_data": "$prev.result.field_data", "x_data": "$prev.result.x_grid", "y_data": "$prev.result.y_grid"},
    },
    "lcapy_to_control": {
        "from": "lcapy",
        "to": "control",
        "type": "sequential",
        "description": "Lcapy symbolic transfer function → python-control Bode/Nyquist analysis",
        "default_param_map": {"numerator": "$prev.result.transfer_numerator", "denominator": "$prev.result.transfer_denominator"},
    },
    "networkx_to_manim": {
        "from": "networkx",
        "to": "manim",
        "type": "sequential",
        "description": "NetworkX graph data → animated graph traversal visualization",
        "default_param_map": {"nodes": "$prev.result.nodes", "edges": "$prev.result.edges"},
    },
    "phiflow_to_matplotlib": {
        "from": "phiflow",
        "to": "matplotlib",
        "type": "sequential",
        "description": "PhiFlow fluid velocity/density fields → Matplotlib contour/quiver plot",
        "default_param_map": {"z_data": "$prev.result.field_data", "x_data": "$prev.result.x_grid", "y_data": "$prev.result.y_grid"},
    },
    "qutip_to_manim": {
        "from": "qutip",
        "to": "manim",
        "type": "sequential",
        "description": "QuTiP Bloch vector trajectory → Manim 3D Bloch sphere animation",
        "default_param_map": {
            "simulation_type": "bloch_sphere",
            "trajectory_x": "$prev.result.bloch.x",
            "trajectory_y": "$prev.result.bloch.y",
            "trajectory_z": "$prev.result.bloch.z",
        },
    },
    "sagemath_to_sympy": {
        "from": "sagemath",
        "to": "sympy",
        "type": "sequential",
        "description": "SageMath symbolic result → SymPy expression for further analysis",
        "default_param_map": {"expression": "$prev.result.result"},
    },
    "sympy_to_sagemath": {
        "from": "sympy",
        "to": "sagemath",
        "type": "sequential",
        "description": "SymPy expression → SageMath for algebra/number theory computations",
        "default_param_map": {"polynomials": "$prev.result.result"},
    },
    "gap_to_qiskit": {
        "from": "gap",
        "to": "qiskit",
        "type": "sequential",
        "description": "GAP stabilizer generators → Qiskit syndrome measurement circuits",
        "default_param_map": {
            "simulation_type": "stabilizer_codes",
            "generators": "$prev.result.generators",
        },
    },
    "gmsh_to_su2": {
        "from": "gmsh",
        "to": "su2",
        "type": "sequential",
        "description": "Gmsh mesh (.msh) → SU2 native mesh format",
        "default_param_map": {"mesh_file": "$prev.result.mesh_file_path"},
    },
    "gmsh_to_firedrake": {
        "from": "gmsh",
        "to": "firedrake",
        "type": "sequential",
        "description": "Gmsh mesh (.msh) → Firedrake mesh import",
        "default_param_map": {"mesh_file": "$prev.result.mesh_file_path"},
    },
    "openfoam_to_vtk": {
        "from": "openfoam",
        "to": "vtk",
        "type": "sequential",
        "description": "OpenFOAM velocity/pressure fields → VTK visualization",
        "default_param_map": {"field_data": "$prev.result.field_data", "x_grid": "$prev.result.x_grid", "y_grid": "$prev.result.y_grid"},
    },
    "fenics_to_vtk": {
        "from": "fenics",
        "to": "vtk",
        "type": "sequential",
        "description": "FEniCS solution fields → VTK rendering",
        "default_param_map": {"field_data": "$prev.result.field_data", "x_grid": "$prev.result.x_grid", "y_grid": "$prev.result.y_grid"},
    },
    "dedalus_to_vtk": {
        "from": "dedalus",
        "to": "vtk",
        "type": "sequential",
        "description": "Dedalus spectral solution → VTK field visualization",
        "default_param_map": {"field_data": "$prev.result.field_data", "x_grid": "$prev.result.x_grid", "y_grid": "$prev.result.y_grid"},
    },
    "phiflow_to_vtk": {
        "from": "phiflow",
        "to": "vtk",
        "type": "sequential",
        "description": "PhiFlow fluid fields → VTK rendering",
        "default_param_map": {"field_data": "$prev.result.field_data", "x_grid": "$prev.result.x_grid", "y_grid": "$prev.result.y_grid"},
    },
    # --- Tier 1 couplings: cross-tool connections between existing tools ---
    "qutip_to_psi4": {
        "from": "qutip",
        "to": "psi4",
        "type": "sequential",
        "description": "QuTiP quantum state → Psi4 molecular electronic structure",
        "default_param_map": {},
    },
    "pybullet_to_elmer": {
        "from": "pybullet",
        "to": "elmer",
        "type": "sequential",
        "description": "PyBullet contact forces/geometry → Elmer structural FEM analysis",
        "default_param_map": {"contact_forces": "$prev.result.collisions"},
    },
    "fenics_to_pyspice": {
        "from": "fenics",
        "to": "pyspice",
        "type": "sequential",
        "description": "FEniCS EM field solution → PySpice parasitic extraction",
        "default_param_map": {"field_data": "$prev.result.field_data"},
    },
    "elmer_to_pyspice": {
        "from": "elmer",
        "to": "pyspice",
        "type": "sequential",
        "description": "Elmer EM/thermal solution → PySpice circuit parameters",
        "default_param_map": {"field_data": "$prev.result.field_data"},
    },
    "openmm_to_basico": {
        "from": "openmm",
        "to": "basico",
        "type": "sequential",
        "description": "OpenMM binding energies → BasiCO reaction rate constants",
        "default_param_map": {"binding_energy": "$prev.result.potential_energy"},
    },
    "openmm_to_tellurium": {
        "from": "openmm",
        "to": "tellurium",
        "type": "sequential",
        "description": "OpenMM structural data → Tellurium pathway parameters",
        "default_param_map": {"structural_data": "$prev.result"},
    },
    "fenics_to_basico": {
        "from": "fenics",
        "to": "basico",
        "type": "sequential",
        "description": "FEniCS diffusion fields → BasiCO spatial reaction-diffusion",
        "default_param_map": {"diffusion_field": "$prev.result.field_data"},
    },
    "fenics_to_tellurium": {
        "from": "fenics",
        "to": "tellurium",
        "type": "sequential",
        "description": "FEniCS continuum solution → Tellurium pathway boundary conditions",
        "default_param_map": {"boundary_data": "$prev.result.field_data"},
    },
    "rdkit_to_psi4": {
        "from": "rdkit",
        "to": "psi4",
        "type": "sequential",
        "description": "RDKit 3D conformer → Psi4 quantum chemistry (SAPT, energy)",
        "default_param_map": {"geometry": "$prev.result.atom_coords_xyz"},
    },
    "rdkit_to_openmm": {
        "from": "rdkit",
        "to": "openmm",
        "type": "sequential",
        "description": "RDKit molecular structure → OpenMM molecular dynamics",
        "default_param_map": {"pdb_content": "$prev.result.pdb_block"},
    },
    "rdkit_to_mdanalysis": {
        "from": "rdkit",
        "to": "mdanalysis",
        "type": "sequential",
        "description": "RDKit conformer ensemble → MDAnalysis trajectory analysis",
        "default_param_map": {"structure_data": "$prev.result"},
    },
    "rdkit_to_pyrosetta": {
        "from": "rdkit",
        "to": "pyrosetta",
        "type": "sequential",
        "description": "RDKit ligand → PyRosetta docking (DEFERRED — PyRosetta not yet available)",
        "default_param_map": {"ligand_sdf": "$prev.result.sdf_block"},
        "deferred": True,
    },
    "cantera_to_fenics": {
        "from": "cantera",
        "to": "fenics",
        "type": "sequential",
        "description": "Cantera flame/reactor → FEniCS reactive flow continuum model",
        "default_param_map": {"source_term": "$prev.result.heat_release_rate"},
    },
    "cantera_to_basico": {
        "from": "cantera",
        "to": "basico",
        "type": "sequential",
        "description": "Cantera kinetics → BasiCO reaction network (chemical ↔ biological)",
        "default_param_map": {"species_concentrations": "$prev.result.species"},
    },
    "cantera_to_tellurium": {
        "from": "cantera",
        "to": "tellurium",
        "type": "sequential",
        "description": "Cantera species data → Tellurium pathway model parameters",
        "default_param_map": {"species_data": "$prev.result.species"},
    },
    "cantera_to_elmer": {
        "from": "cantera",
        "to": "elmer",
        "type": "sequential",
        "description": "Cantera thermal data → Elmer thermal-structural FEM",
        "default_param_map": {"temperature_profile": "$prev.result.temperature"},
    },
    "qe_to_lammps": {
        "from": "qe",
        "to": "lammps",
        "type": "sequential",
        "description": "QE DFT-fitted potential → LAMMPS large-scale MD with ab initio parameters",
        "default_param_map": {"potential_data": "$prev.result"},
    },
    "qe_to_cantera": {
        "from": "qe",
        "to": "cantera",
        "type": "sequential",
        "description": "QE surface energies → Cantera heterogeneous catalysis mechanisms",
        "default_param_map": {"surface_energies": "$prev.result.total_energy"},
    },
    "cantera_to_lammps": {
        "from": "cantera",
        "to": "lammps",
        "type": "sequential",
        "description": "Cantera reactive species → LAMMPS ReaxFF molecular dynamics",
        "default_param_map": {"species_data": "$prev.result.species"},
    },
    "rdkit_to_cantera": {
        "from": "rdkit",
        "to": "cantera",
        "type": "sequential",
        "description": "RDKit molecular properties → Cantera thermodynamic data",
        "default_param_map": {"smiles": "$prev.result.smiles", "molecular_weight": "$prev.result.molecular_weight"},
    },
    "rdkit_to_lammps": {
        "from": "rdkit",
        "to": "lammps",
        "type": "sequential",
        "description": "RDKit 3D conformer → LAMMPS molecular system setup",
        "default_param_map": {"coordinates": "$prev.result.conformer_coordinates"},
    },
    "sympy_to_cantera": {
        "from": "sympy",
        "to": "cantera",
        "type": "sequential",
        "description": "SymPy symbolic rate expressions → Cantera custom reaction mechanisms",
        "default_param_map": {"rate_expression": "$prev.result.expression"},
    },
    "sympy_to_qutip": {
        "from": "sympy",
        "to": "qutip",
        "type": "sequential",
        "description": "SymPy symbolic Hamiltonian → QuTiP quantum dynamics",
        "default_param_map": {"hamiltonian_expr": "$prev.result.expression"},
    },
    "sympy_to_einsteinpy": {
        "from": "sympy",
        "to": "einsteinpy",
        "type": "sequential",
        "description": "SymPy metric tensor components → EinsteinPy geodesic integration",
        "default_param_map": {"metric_expr": "$prev.result.expression"},
    },
    "sagemath_to_gap": {
        "from": "sagemath",
        "to": "gap",
        "type": "sequential",
        "description": "SageMath group/algebra computation → GAP advanced group theory",
        "default_param_map": {"group_data": "$prev.result.result"},
    },
    "gap_to_sagemath": {
        "from": "gap",
        "to": "sagemath",
        "type": "sequential",
        "description": "GAP group structure → SageMath algebraic geometry/number theory",
        "default_param_map": {"group_data": "$prev.result"},
    },
    "sagemath_to_einsteinpy": {
        "from": "sagemath",
        "to": "einsteinpy",
        "type": "sequential",
        "description": "SageMath differential geometry → EinsteinPy spacetime analysis",
        "default_param_map": {"metric_data": "$prev.result.result"},
    },
    "gmsh_to_elmer": {
        "from": "gmsh",
        "to": "elmer",
        "type": "sequential",
        "description": "Gmsh mesh → Elmer FEM solver mesh import",
        "default_param_map": {"mesh_file": "$prev.result.mesh_file_path"},
    },
    "lcapy_to_sympy": {
        "from": "lcapy",
        "to": "sympy",
        "type": "sequential",
        "description": "Lcapy symbolic circuit expression → SymPy general symbolic analysis",
        "default_param_map": {"expression": "$prev.result.transfer_function_str"},
    },
    "pennylane_to_qutip": {
        "from": "pennylane",
        "to": "qutip",
        "type": "sequential",
        "description": "PennyLane quantum circuit → QuTiP open quantum system simulation",
        "default_param_map": {"gate_sequence": "$prev.result.gate_sequence"},
    },
    "pennylane_to_pyscf": {
        "from": "pennylane",
        "to": "pyscf",
        "type": "sequential",
        "description": "PennyLane VQE molecular parameters → PySCF electronic structure",
        "default_param_map": {"geometry": "$prev.result.molecular_geometry"},
    },
    "sympy_to_pyspice": {
        "from": "sympy",
        "to": "pyspice",
        "type": "sequential",
        "description": "SymPy symbolic circuit equations → PySpice numerical simulation",
        "default_param_map": {"circuit_expr": "$prev.result.expression"},
    },
    "sympy_to_qiskit": {
        "from": "sympy",
        "to": "qiskit",
        "type": "sequential",
        "description": "SymPy symbolic Hamiltonian → Qiskit quantum circuit synthesis",
        "default_param_map": {"hamiltonian_expr": "$prev.result.expression"},
    },
    "rdkit_to_qiskit": {
        "from": "rdkit",
        "to": "qiskit",
        "type": "sequential",
        "description": "RDKit molecular data → Qiskit Nature molecular VQE",
        "default_param_map": {"smiles": "$prev.result.smiles"},
    },
    # --- Open Babel couplings ---
    "rdkit_to_openbabel": {
        "from": "rdkit",
        "to": "openbabel",
        "type": "sequential",
        "description": "RDKit SMILES/conformer → Open Babel format conversion or 3D optimization",
        "default_param_map": {"source_data": "$prev.result.smiles", "source_format": "smi"},
    },
    "openbabel_to_rdkit": {
        "from": "openbabel",
        "to": "rdkit",
        "type": "sequential",
        "description": "Open Babel output → RDKit for descriptor/fingerprint analysis",
        "default_param_map": {"smiles": "$prev.result.output_data"},
    },
    "openbabel_to_pyscf": {
        "from": "openbabel",
        "to": "pyscf",
        "type": "sequential",
        "description": "Open Babel XYZ coordinates → PySCF electronic structure calculation",
        "default_param_map": {"geometry": "$prev.result.output_xyz"},
    },
    "openbabel_to_psi4": {
        "from": "openbabel",
        "to": "psi4",
        "type": "sequential",
        "description": "Open Babel optimized geometry → Psi4 quantum chemistry",
        "default_param_map": {"geometry": "$prev.result.output_xyz"},
    },
    "openbabel_to_lammps": {
        "from": "openbabel",
        "to": "lammps",
        "type": "sequential",
        "description": "Open Babel → LAMMPS data file for materials MD",
        "default_param_map": {"molecule_data": "$prev.result.output_data"},
    },
    "openbabel_to_gromacs": {
        "from": "openbabel",
        "to": "gromacs",
        "type": "sequential",
        "description": "Open Babel → GROMACS topology/coordinate files",
        "default_param_map": {"molecule_data": "$prev.result.output_data"},
    },
    "openbabel_to_qe": {
        "from": "openbabel",
        "to": "qe",
        "type": "sequential",
        "description": "Open Babel molecular geometry → Quantum ESPRESSO input",
        "default_param_map": {"coordinates": "$prev.result.coordinates", "elements": "$prev.result.elements"},
    },
    "openbabel_to_openmm": {
        "from": "openbabel",
        "to": "openmm",
        "type": "sequential",
        "description": "Open Babel PDB output → OpenMM molecular dynamics",
        "default_param_map": {"pdb_content": "$prev.result.output_pdb"},
    },
    "openbabel_to_namd": {
        "from": "openbabel",
        "to": "namd",
        "type": "sequential",
        "description": "Open Babel PDB output → NAMD molecular dynamics",
        "default_param_map": {"pdb_content": "$prev.result.output_pdb"},
    },
    "mdanalysis_to_openbabel": {
        "from": "mdanalysis",
        "to": "openbabel",
        "type": "sequential",
        "description": "MDAnalysis extracted frame → Open Babel format conversion",
        "default_param_map": {"source_data": "$prev.result.pdb_frame", "source_format": "pdb"},
    },
    "einsteinpy_to_rebound": {
        "from": "einsteinpy",
        "to": "rebound",
        "type": "sequential",
        "description": "EinsteinPy metric parameters → REBOUND N-body with GR corrections (REBOUNDx)",
        "default_param_map": {
            "gr_correction": "gr_full",
            "M": "$prev.result.M",
        },
    },
    # --- COMSOL deferred coupling stubs ---
    "comsol_pyspice": {
        "from": "comsol",
        "to": "pyspice",
        "type": "sequential",
        "description": "COMSOL EM field → PySpice circuit co-simulation (DEFERRED — COMSOL not licensed)",
        "default_param_map": {},
        "deferred": True,
    },
    "cantera_to_comsol": {
        "from": "cantera",
        "to": "comsol",
        "type": "sequential",
        "description": "Cantera reaction kinetics → COMSOL reactor CFD (DEFERRED — COMSOL not licensed)",
        "default_param_map": {},
        "deferred": True,
    },
    "gmsh_to_comsol": {
        "from": "gmsh",
        "to": "comsol",
        "type": "sequential",
        "description": "Gmsh mesh → COMSOL mesh import (DEFERRED — COMSOL not licensed)",
        "default_param_map": {"mesh_file": "$prev.result.mesh_file_path"},
        "deferred": True,
    },
    "lammps_to_comsol": {
        "from": "lammps",
        "to": "comsol",
        "type": "sequential",
        "description": "LAMMPS atomistic → COMSOL continuum (DEFERRED — COMSOL not licensed)",
        "default_param_map": {},
        "deferred": True,
    },
    "qe_to_comsol": {
        "from": "qe",
        "to": "comsol",
        "type": "sequential",
        "description": "QE electronic → COMSOL device simulation (DEFERRED — COMSOL not licensed)",
        "default_param_map": {},
        "deferred": True,
    },
    "sympy_to_comsol": {
        "from": "sympy",
        "to": "comsol",
        "type": "sequential",
        "description": "SymPy symbolic PDE → COMSOL solver (DEFERRED — COMSOL not licensed)",
        "default_param_map": {},
        "deferred": True,
    },
    # --- AlphaFold deferred coupling stubs ---
    "alphafold_to_openmm": {
        "from": "alphafold",
        "to": "openmm",
        "type": "sequential",
        "description": "AlphaFold predicted structure → OpenMM MD refinement (DEFERRED — AlphaFold not available)",
        "default_param_map": {"pdb_content": "$prev.result.pdb_content"},
        "deferred": True,
    },
    "alphafold_to_pyrosetta": {
        "from": "alphafold",
        "to": "pyrosetta",
        "type": "sequential",
        "description": "AlphaFold structure → PyRosetta design/refinement (DEFERRED — both tools not available)",
        "default_param_map": {},
        "deferred": True,
    },
    "slim_to_alphafold": {
        "from": "slim",
        "to": "alphafold",
        "type": "sequential",
        "description": "SLiM mutant sequences → AlphaFold structure prediction (DEFERRED — both tools not available)",
        "default_param_map": {},
        "deferred": True,
    },
    # --- Phase 10: Biology branch couplings ---
    "slim_to_tskit": {
        "from": "slim",
        "to": "tskit",
        "type": "sequential",
        "description": "SLiM tree sequence → tskit diversity/Fst analysis",
        "default_param_map": {"source_job_id": "$prev.job_id"},
    },
    "msprime_to_tskit": {
        "from": "msprime",
        "to": "tskit",
        "type": "sequential",
        "description": "msprime tree sequence → tskit post-hoc analysis",
        "default_param_map": {"source_job_id": "$prev.job_id"},
    },
    "msprime_to_slim": {
        "from": "msprime",
        "to": "slim",
        "type": "sequential",
        "description": "msprime coalescent parameters → SLiM forward-time simulation",
        "default_param_map": {"demographic_data": "$prev.result"},
    },
    "slim_to_msprime": {
        "from": "slim",
        "to": "msprime",
        "type": "sequential",
        "description": "SLiM forward simulation → msprime coalescent recapitation parameters",
        "default_param_map": {"source_job_id": "$prev.job_id"},
    },
    "pyrosetta_to_openmm": {
        "from": "pyrosetta",
        "to": "openmm",
        "type": "sequential",
        "description": "PyRosetta modeled structure → OpenMM MD refinement (DEFERRED — PyRosetta not licensed)",
        "default_param_map": {"pdb_content": "$prev.result.pdb_content"},
        "deferred": True,
    },
    "pyrosetta_to_basico": {
        "from": "pyrosetta",
        "to": "basico",
        "type": "sequential",
        "description": "PyRosetta binding energies → BasiCO reaction rate constants (DEFERRED — PyRosetta not licensed)",
        "default_param_map": {"binding_energy": "$prev.result.binding_energy"},
        "deferred": True,
    },
    "pyrosetta_to_tellurium": {
        "from": "pyrosetta",
        "to": "tellurium",
        "type": "sequential",
        "description": "PyRosetta structural data → Tellurium pathway parameters (DEFERRED — PyRosetta not licensed)",
        "default_param_map": {"structural_data": "$prev.result"},
        "deferred": True,
    },
    "slim_to_pyrosetta": {
        "from": "slim",
        "to": "pyrosetta",
        "type": "sequential",
        "description": "SLiM mutant protein sequences → PyRosetta structure prediction (DEFERRED — PyRosetta not licensed)",
        "default_param_map": {"sequence": "$prev.result.mutant_sequence"},
        "deferred": True,
    },
    "slim_to_simupop": {
        "from": "slim",
        "to": "simupop",
        "type": "sequential",
        "description": "SLiM population parameters → simuPOP alternative forward-time model",
        "default_param_map": {
            "population_size": "$prev.result.population_size",
            "n_generations": "$prev.result.n_generations",
        },
    },
    "simupop_to_msprime": {
        "from": "simupop",
        "to": "msprime",
        "type": "sequential",
        "description": "simuPOP population size history → msprime demographic model",
        "default_param_map": {
            "population_size": "$prev.result.population_size",
        },
    },
    # --- Phase 11: Missing Tier 1 couplings ---
    "psi4_to_openmm_qmmm": {
        "from": "psi4",
        "to": "openmm",
        "type": "concurrent",
        "description": "QM/MM: Psi4 QM + OpenMM MM via PyDFT-QMMM",
    },
    "gromacs_to_openmm": {
        "from": "gromacs",
        "to": "openmm",
        "type": "sequential",
        "description": "GROMACS topology → OpenMM System (force field interop)",
        "default_param_map": {"topology_data": "$prev.result"},
    },
    "einsteinpy_to_etk": {
        "from": "einsteinpy",
        "to": "einstein_toolkit",
        "type": "sequential",
        "description": "EinsteinPy analytical metric → Einstein Toolkit initial data validation",
        "default_param_map": {"metric_data": "$prev.result"},
    },
    "etk_to_rebound": {
        "from": "einstein_toolkit",
        "to": "rebound",
        "type": "sequential",
        "description": "Einstein Toolkit strong-field corrections → REBOUNDx additional forces",
        "default_param_map": {"gr_correction": "gr_full", "metric_data": "$prev.result"},
    },
    "openbabel_to_pyrosetta": {
        "from": "openbabel",
        "to": "pyrosetta",
        "type": "sequential",
        "description": "Open Babel ligand format → PyRosetta docking input (DEFERRED)",
        "default_param_map": {"ligand_data": "$prev.result.output_data"},
        "deferred": True,
    },
    # --- Phase 11: Tier 2 couplings (#76-103) ---
    "psi4_to_qiskit": {
        "from": "psi4",
        "to": "qiskit",
        "type": "sequential",
        "description": "Qiskit Nature Psi4 driver for molecular integrals",
        "default_param_map": {"molecular_data": "$prev.result"},
    },
    "psi4_to_pennylane": {
        "from": "psi4",
        "to": "pennylane",
        "type": "sequential",
        "description": "pennylane-psi4 plugin for quantum chemistry",
        "default_param_map": {"molecular_data": "$prev.result"},
    },
    "pyscf_to_cantera": {
        "from": "pyscf",
        "to": "cantera",
        "type": "sequential",
        "description": "Transition state theory: QC barriers → rate constants",
        "default_param_map": {"activation_energy": "$prev.result.total_energy"},
    },
    "psi4_to_cantera": {
        "from": "psi4",
        "to": "cantera",
        "type": "sequential",
        "description": "Transition state theory via Psi4: QC barriers → rate constants",
        "default_param_map": {"activation_energy": "$prev.result.total_energy"},
    },
    "pyscf_to_pyrosetta": {
        "from": "pyscf",
        "to": "pyrosetta",
        "type": "sequential",
        "description": "QM-informed ligand scoring (DEFERRED)",
        "default_param_map": {"qm_data": "$prev.result"},
        "deferred": True,
    },
    "psi4_to_pyrosetta": {
        "from": "psi4",
        "to": "pyrosetta",
        "type": "sequential",
        "description": "QM-informed ligand scoring via Psi4 (DEFERRED)",
        "default_param_map": {"qm_data": "$prev.result"},
        "deferred": True,
    },
    "pyscf_to_qe": {
        "from": "pyscf",
        "to": "qe",
        "type": "sequential",
        "description": "pyscf.pbc molecular ↔ periodic DFT bridge",
        "default_param_map": {"molecular_data": "$prev.result"},
    },
    "psi4_to_qe": {
        "from": "psi4",
        "to": "qe",
        "type": "sequential",
        "description": "Molecular ↔ periodic DFT bridge via Psi4",
        "default_param_map": {"molecular_data": "$prev.result"},
    },
    "openmm_to_lammps": {
        "from": "openmm",
        "to": "lammps",
        "type": "sequential",
        "description": "Force field conversion, bio+materials multiscale",
        "default_param_map": {"structure_data": "$prev.result"},
    },
    "gromacs_to_lammps": {
        "from": "gromacs",
        "to": "lammps",
        "type": "sequential",
        "description": "Trajectory/topology interconversion via MDAnalysis",
        "default_param_map": {"trajectory_data": "$prev.result"},
    },
    "namd_to_lammps": {
        "from": "namd",
        "to": "lammps",
        "type": "sequential",
        "description": "NAMD trajectory/topology → LAMMPS interconversion",
        "default_param_map": {"trajectory_data": "$prev.result"},
    },
    "openmm_to_qe": {
        "from": "openmm",
        "to": "qe",
        "type": "sequential",
        "description": "QE-derived force constants → OpenMM FF params",
        "default_param_map": {"structure_data": "$prev.result"},
    },
    "gromacs_to_qe": {
        "from": "gromacs",
        "to": "qe",
        "type": "sequential",
        "description": "QE-derived parameters → GROMACS topology",
        "default_param_map": {"structure_data": "$prev.result"},
    },
    "lammps_to_elmer": {
        "from": "lammps",
        "to": "elmer",
        "type": "sequential",
        "description": "Atomic → continuum: elastic constants, thermal properties",
        "default_param_map": {"material_properties": "$prev.result"},
    },
    "qe_to_fenics": {
        "from": "qe",
        "to": "fenics",
        "type": "sequential",
        "description": "DFT material properties → FEM continuum simulation",
        "default_param_map": {"material_data": "$prev.result"},
    },
    "qe_to_elmer": {
        "from": "qe",
        "to": "elmer",
        "type": "sequential",
        "description": "DFT material properties → Elmer FEM continuum simulation",
        "default_param_map": {"material_data": "$prev.result"},
    },
    "sympy_to_elmer": {
        "from": "sympy",
        "to": "elmer",
        "type": "sequential",
        "description": "Symbolic PDE → Elmer .sif solver input",
        "default_param_map": {"pde_expression": "$prev.result.expression"},
    },
    "basico_to_sympy": {
        "from": "basico",
        "to": "sympy",
        "type": "sequential",
        "description": "Symbolic analysis/stability of systems biology ODEs",
        "default_param_map": {"expression": "$prev.result.ode_system"},
    },
    "tellurium_to_sympy": {
        "from": "tellurium",
        "to": "sympy",
        "type": "sequential",
        "description": "Symbolic analysis of Tellurium pathway model ODEs",
        "default_param_map": {"expression": "$prev.result.ode_system"},
    },
    "qmmm_to_rdkit": {
        "from": "qmmm",
        "to": "rdkit",
        "type": "sequential",
        "description": "RDKit ligand parameterization for ASH QM/MM",
        "default_param_map": {"smiles": "$prev.result.ligand_smiles"},
    },
    "qmmm_to_openbabel": {
        "from": "qmmm",
        "to": "openbabel",
        "type": "sequential",
        "description": "Open Babel format conversion for ASH input",
        "default_param_map": {"source_data": "$prev.result.structure_data"},
    },
    "rdkit_to_qe": {
        "from": "rdkit",
        "to": "qe",
        "type": "sequential",
        "description": "SMILES → crystal structure prediction input",
        "default_param_map": {"coordinates": "$prev.result.conformer_coordinates", "elements": "$prev.result.elements"},
    },
    "gmsh_to_lammps": {
        "from": "gmsh",
        "to": "lammps",
        "type": "sequential",
        "description": "FEM mesh for hybrid continuum-atomistic regions",
        "default_param_map": {"mesh_data": "$prev.result.mesh_file_path"},
    },
    "sagemath_to_elmer": {
        "from": "sagemath",
        "to": "elmer",
        "type": "sequential",
        "description": "Differential geometry for curved-space FEM (via SymPy)",
        "default_param_map": {"geometry_data": "$prev.result.result"},
    },
    # --- Phase 11: Tier 3 couplings (#104-128) — research frontier ---
    "qutip_to_qe": {
        "from": "qutip",
        "to": "qe",
        "type": "sequential",
        "description": "Defect qubits in solids (NV centers, quantum dots)",
        "default_param_map": {"qubit_data": "$prev.result"},
    },
    "qutip_to_sagemath": {
        "from": "qutip",
        "to": "sagemath",
        "type": "sequential",
        "description": "Lie algebra representations → quantum operators",
        "default_param_map": {"operator_data": "$prev.result"},
    },
    "qutip_to_gap": {
        "from": "qutip",
        "to": "gap",
        "type": "sequential",
        "description": "Group theory → symmetry-adapted quantum states",
        "default_param_map": {"symmetry_data": "$prev.result"},
    },
    "qutip_to_pyspice": {
        "from": "qutip",
        "to": "pyspice",
        "type": "sequential",
        "description": "Circuit QED: classical readout + quantum dynamics",
        "default_param_map": {"qubit_params": "$prev.result"},
    },
    "qutip_to_lcapy": {
        "from": "qutip",
        "to": "lcapy",
        "type": "sequential",
        "description": "Circuit QED: LC circuit → quantum Hamiltonian (Jaynes-Cummings)",
        "default_param_map": {"circuit_params": "$prev.result"},
    },
    "sympy_to_pennylane": {
        "from": "sympy",
        "to": "pennylane",
        "type": "sequential",
        "description": "Symbolic Hamiltonians → parametric quantum circuits",
        "default_param_map": {"hamiltonian_expr": "$prev.result.expression"},
    },
    "sympy_to_lean4": {
        "from": "sympy",
        "to": "lean4",
        "type": "sequential",
        "description": "Verified symbolic computation: SymPy generates → Lean 4 verifies",
        "default_param_map": {"statement": "$prev.result.expression"},
    },
    "sagemath_to_lean4": {
        "from": "sagemath",
        "to": "lean4",
        "type": "sequential",
        "description": "SageMath computations → Lean 4 formal verification",
        "default_param_map": {"statement": "$prev.result.result"},
    },
    "sagemath_to_lcapy": {
        "from": "sagemath",
        "to": "lcapy",
        "type": "sequential",
        "description": "Advanced symbolic circuit analysis via SymPy bridge",
        "default_param_map": {"expression": "$prev.result.result"},
    },
    "sagemath_to_qiskit": {
        "from": "sagemath",
        "to": "qiskit",
        "type": "sequential",
        "description": "Coding theory → stabilizer codes for QEC",
        "default_param_map": {"code_data": "$prev.result.result"},
    },
    "sagemath_to_pennylane": {
        "from": "sagemath",
        "to": "pennylane",
        "type": "sequential",
        "description": "Symmetry-aware quantum ML via representation theory",
        "default_param_map": {"symmetry_data": "$prev.result.result"},
    },
    "lean4_to_gap": {
        "from": "lean4",
        "to": "gap",
        "type": "sequential",
        "description": "Verified computational algebra",
        "default_param_map": {"proof_data": "$prev.result"},
    },
    "gap_to_qe": {
        "from": "gap",
        "to": "qe",
        "type": "sequential",
        "description": "Crystallographic space groups → Brillouin zone sampling",
        "default_param_map": {"space_group": "$prev.result"},
    },
    "gap_to_pennylane": {
        "from": "gap",
        "to": "pennylane",
        "type": "sequential",
        "description": "Equivariant quantum circuits via group symmetry",
        "default_param_map": {"group_data": "$prev.result"},
    },
    "qe_to_qiskit": {
        "from": "qe",
        "to": "qiskit",
        "type": "sequential",
        "description": "Periodic Hamiltonians → quantum simulation of materials",
        "default_param_map": {"hamiltonian_data": "$prev.result"},
    },
    "qe_to_pennylane": {
        "from": "qe",
        "to": "pennylane",
        "type": "sequential",
        "description": "Quantum algorithms for periodic DFT",
        "default_param_map": {"material_data": "$prev.result"},
    },
    "pyspice_to_qiskit": {
        "from": "pyspice",
        "to": "qiskit",
        "type": "sequential",
        "description": "Classical + quantum circuit co-design for hardware",
        "default_param_map": {"circuit_data": "$prev.result"},
    },
    "pyspice_to_pennylane": {
        "from": "pyspice",
        "to": "pennylane",
        "type": "sequential",
        "description": "Classical + quantum circuit co-design via PennyLane",
        "default_param_map": {"circuit_data": "$prev.result"},
    },
    "lcapy_to_qiskit": {
        "from": "lcapy",
        "to": "qiskit",
        "type": "sequential",
        "description": "Symbolic circuit params (L,C,J) → transmon Hamiltonians",
        "default_param_map": {"circuit_params": "$prev.result"},
    },
    "lcapy_to_pennylane": {
        "from": "lcapy",
        "to": "pennylane",
        "type": "sequential",
        "description": "Symbolic circuit params → differentiable quantum circuits",
        "default_param_map": {"circuit_params": "$prev.result"},
    },
    "simupop_to_tskit": {
        "from": "simupop",
        "to": "tskit",
        "type": "sequential",
        "description": "Genotype matrix → tsinfer → tree sequence",
        "default_param_map": {"genotype_data": "$prev.result"},
    },
    "openbabel_to_cantera": {
        "from": "openbabel",
        "to": "cantera",
        "type": "sequential",
        "description": "Molecular geometry → transport property estimation",
        "default_param_map": {"molecule_data": "$prev.result"},
    },
    "rdkit_to_sympy": {
        "from": "rdkit",
        "to": "sympy",
        "type": "sequential",
        "description": "QSAR symbolic analysis of molecular descriptors",
        "default_param_map": {"expression": "$prev.result.descriptors"},
    },
    "pennylane_to_lammps": {
        "from": "pennylane",
        "to": "lammps",
        "type": "sequential",
        "description": "Quantum neural network potentials for MD (frontier)",
        "default_param_map": {"potential_data": "$prev.result"},
    },
    "lean4_to_sympy": {
        "from": "lean4",
        "to": "sympy",
        "type": "sequential",
        "description": "Verified symbolic computation (verification direction)",
        "default_param_map": {"expression": "$prev.result.proof_term"},
    },
    # --- Optics couplings ---
    "rayoptics_to_lightpipes": {
        "from": "rayoptics",
        "to": "lightpipes",
        "type": "sequential",
        "description": "Ray trace focus → LightPipes wave propagation at focal plane",
        "default_param_map": {"lens_focus.focal_length": "$prev.result.efl"},
    },
    "lightpipes_to_meep": {
        "from": "lightpipes",
        "to": "meep",
        "type": "sequential",
        "description": "Wave optics beam profile → Meep FDTD source field",
        "default_param_map": {"source_field": "$prev.result.intensity"},
    },
    "meep_to_vtk": {
        "from": "meep",
        "to": "vtk",
        "type": "sequential",
        "description": "Meep FDTD field data → VTK 3D isosurface visualization",
        "default_param_map": {"field_data": "$prev.result.field_ez", "x_grid": "$prev.result.x_range", "y_grid": "$prev.result.y_range"},
    },
    "meep_to_matplotlib": {
        "from": "meep",
        "to": "matplotlib",
        "type": "sequential",
        "description": "Meep FDTD spectra/fields → Matplotlib publication plots",
        "default_param_map": {"z_data": "$prev.result.field_ez", "x_data": "$prev.result.x_range", "y_data": "$prev.result.y_range"},
    },
    "lightpipes_to_matplotlib": {
        "from": "lightpipes",
        "to": "matplotlib",
        "type": "sequential",
        "description": "Diffraction/interference pattern → Matplotlib publication plot",
        "default_param_map": {"z_data": "$prev.result.intensity", "x_data": "$prev.result.x_mm"},
    },
    "strawberryfields_to_qutip": {
        "from": "strawberryfields",
        "to": "qutip",
        "type": "sequential",
        "description": "Photonic Gaussian state → QuTiP cavity QED dynamics",
        "default_param_map": {"initial_state_data": "$prev.result"},
    },
    "qutip_to_strawberryfields": {
        "from": "qutip",
        "to": "strawberryfields",
        "type": "sequential",
        "description": "Quantum state → Strawberry Fields photonic circuit input",
        "default_param_map": {"state_data": "$prev.result"},
    },
    "strawberryfields_to_pennylane": {
        "from": "strawberryfields",
        "to": "pennylane",
        "type": "sequential",
        "description": "Photonic circuit → PennyLane hybrid quantum-classical ML",
        "default_param_map": {"circuit_data": "$prev.result"},
    },
    "pennylane_to_strawberryfields": {
        "from": "pennylane",
        "to": "strawberryfields",
        "type": "sequential",
        "description": "Optimized QML parameters → Strawberry Fields photonic circuit",
        "default_param_map": {"optimized_params": "$prev.result"},
    },
    "meep_to_fenics": {
        "from": "meep",
        "to": "fenics",
        "type": "sequential",
        "description": "Meep EM field absorption → FEniCS thermal FEM (laser heating)",
        "default_param_map": {"source_term": "$prev.result.field_ez"},
    },
    "sympy_to_rayoptics": {
        "from": "sympy",
        "to": "rayoptics",
        "type": "sequential",
        "description": "Symbolic lens equation → RayOptics ray trace validation",
        "default_param_map": {"singlet_lens.efl": "$prev.result.expression"},
    },
    "sympy_to_lightpipes": {
        "from": "sympy",
        "to": "lightpipes",
        "type": "sequential",
        "description": "Symbolic diffraction formula → LightPipes wave simulation",
        "default_param_map": {"double_slit.slit_separation": "$prev.result.expression"},
    },
    "gmsh_to_meep": {
        "from": "gmsh",
        "to": "meep",
        "type": "sequential",
        "description": "Gmsh mesh geometry → Meep FDTD computational domain",
        "default_param_map": {"mesh_file": "$prev.result.mesh_file_path"},
    },
}

# Pipeline test presets — JSON files for POST /api/pipeline testing
PIPELINE_PRESETS = {
    "pipeline_quantum_to_organism": {"pipeline": "quantum_to_organism", "label": "Quantum-to-Organism", "example_file": "pipeline_quantum_to_organism.json"},
    "pipeline_mercury_precession": {"pipeline": "mercury_precession", "label": "Mercury GR Precession", "example_file": "pipeline_mercury_precession.json"},
    "pipeline_qmmm_enzyme": {"pipeline": "qmmm_enzyme", "label": "QM/MM Enzyme Catalysis", "example_file": "pipeline_qmmm_enzyme.json"},
    "pipeline_evolution_structure": {"pipeline": "evolution_structure", "label": "Evolution → Structure Feedback", "example_file": "pipeline_evolution_structure.json"},
    "pipeline_multiscale_tissue": {"pipeline": "multiscale_tissue", "label": "Multiscale Tissue Modeling", "example_file": "pipeline_multiscale_tissue.json"},
    "pipeline_drug_discovery": {"pipeline": "drug_discovery", "label": "Drug Discovery", "example_file": "pipeline_drug_discovery.json"},
    "pipeline_materials_discovery": {"pipeline": "materials_discovery", "label": "Materials Discovery", "example_file": "pipeline_materials_discovery.json"},
    "pipeline_reactive_multiphysics": {"pipeline": "reactive_multiphysics", "label": "Reactive Multiphysics", "example_file": "pipeline_reactive_multiphysics.json"},
    "pipeline_math_verification": {"pipeline": "math_verification", "label": "Mathematics Verification Loop", "example_file": "pipeline_math_verification.json"},
    "pipeline_classical_circuit": {"pipeline": "classical_circuit", "label": "Classical Circuit Design", "example_file": "pipeline_classical_circuit.json"},
    "pipeline_quantum_chemistry_qc": {"pipeline": "quantum_chemistry_qc", "label": "QC on Quantum Computers", "example_file": "pipeline_quantum_chemistry_qc.json"},
    "pipeline_photonic_design": {"pipeline": "photonic_design", "label": "Photonic Device Design", "example_file": "pipeline_photonic_design.json"},
}

# Coupling test presets — JSON files for POST /api/pipeline testing of individual couplings
COUPLING_PRESETS = {k: {"coupling": k, "label": v["description"], "from": v["from"], "to": v["to"], "example_file": f"coupling_{k}.json"} for k, v in COUPLINGS.items() if not v.get("deferred")}
