"""Academic export engine — CSV, JSON, LaTeX, PDF generation from simulation results."""

import csv
import io
import json
import os
import uuid
from datetime import datetime, timezone

from config import settings
import results as results_store


def _ensure_export_dir():
    os.makedirs(settings.export_dir, exist_ok=True)


def _flatten_dict(d: dict, parent_key: str = "", sep: str = ".") -> dict:
    """Flatten a nested dict into dot-path keys."""
    items = {}
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.update(_flatten_dict(v, new_key, sep))
        elif isinstance(v, list):
            # Store list length and first few elements as summary
            items[new_key] = str(v) if len(v) <= 5 else f"[{len(v)} items]"
        else:
            items[new_key] = v
    return items


def _collect_results(job_ids: list[str], project: str) -> list[dict]:
    """Fetch and flatten results for the given job_ids."""
    results = []
    for job_id in job_ids:
        raw = results_store.get_result(job_id, project)
        if raw is None:
            # Try Celery backend fallback
            raw = results_store.get_result_data(job_id, project)
        if raw is not None:
            flat = _flatten_dict(raw)
            flat["_job_id"] = job_id
            results.append(flat)
    return results


def _filter_columns(results: list[dict], columns: list[str] | None) -> tuple[list[str], list[dict]]:
    """Determine column order and filter results."""
    if columns:
        # Use specified columns, always include _job_id
        col_set = ["_job_id"] + [c for c in columns if c != "_job_id"]
    else:
        # Collect all unique keys across results
        col_set = []
        seen = set()
        for r in results:
            for k in r.keys():
                if k not in seen:
                    seen.add(k)
                    col_set.append(k)
    return col_set, results


def _to_csv(results: list[dict], columns: list[str]) -> str:
    """Generate CSV string."""
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=columns, extrasaction="ignore")
    writer.writeheader()
    for row in results:
        writer.writerow({c: row.get(c, "") for c in columns})
    return output.getvalue()


def _to_json(results: list[dict], columns: list[str]) -> str:
    """Generate filtered JSON array."""
    filtered = []
    for row in results:
        filtered.append({c: row.get(c) for c in columns if c in row})
    return json.dumps(filtered, indent=2, default=str)


def _to_latex(results: list[dict], columns: list[str], title: str | None) -> str:
    """Generate LaTeX tabular with booktabs formatting."""
    lines = []
    lines.append("% Auto-generated by totalSimulation")
    lines.append("% Requires: \\usepackage{booktabs}")
    lines.append("")
    if title:
        lines.append(f"\\begin{{table}}[htbp]")
        lines.append(f"\\centering")
        lines.append(f"\\caption{{{_latex_escape(title)}}}")

    # Column spec
    col_spec = "l" * len(columns)
    lines.append(f"\\begin{{tabular}}{{{col_spec}}}")
    lines.append("\\toprule")

    # Header
    headers = " & ".join(_latex_escape(c) for c in columns)
    lines.append(f"{headers} \\\\")
    lines.append("\\midrule")

    # Data rows
    for row in results:
        cells = []
        for c in columns:
            val = row.get(c, "")
            if isinstance(val, float):
                cells.append(f"{val:.6g}")
            else:
                cells.append(_latex_escape(str(val)))
        lines.append(" & ".join(cells) + " \\\\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    if title:
        lines.append("\\end{table}")
    lines.append("")
    return "\n".join(lines)


def _latex_escape(text: str) -> str:
    """Escape special LaTeX characters."""
    replacements = {
        "&": "\\&", "%": "\\%", "$": "\\$", "#": "\\#",
        "_": "\\_", "{": "\\{", "}": "\\}", "~": "\\textasciitilde{}",
        "^": "\\textasciicircum{}",
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text


def _to_pdf(results: list[dict], columns: list[str], title: str | None) -> bytes:
    """Generate PDF using reportlab."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter, landscape
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet

    buffer = io.BytesIO()
    page_size = landscape(letter) if len(columns) > 5 else letter
    doc = SimpleDocTemplate(buffer, pagesize=page_size,
                            leftMargin=0.5 * inch, rightMargin=0.5 * inch)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    if title:
        elements.append(Paragraph(title, styles["Title"]))
    else:
        elements.append(Paragraph("Simulation Results", styles["Title"]))

    elements.append(Paragraph(
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} | "
        f"Results: {len(results)}",
        styles["Normal"]
    ))
    elements.append(Spacer(1, 0.3 * inch))

    # Build table data
    table_data = [columns]  # header row
    for row in results:
        row_data = []
        for c in columns:
            val = row.get(c, "")
            if isinstance(val, float):
                row_data.append(f"{val:.6g}")
            else:
                s = str(val)
                row_data.append(s[:40] + "..." if len(s) > 40 else s)
        table_data.append(row_data)

    # Determine column widths
    available_width = page_size[0] - 1 * inch
    col_width = available_width / len(columns)

    table = Table(table_data, colWidths=[col_width] * len(columns))
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTSIZE", (0, 1), (-1, -1), 7),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#334155")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    elements.append(table)

    doc.build(elements)
    return buffer.getvalue()


def export_results(job_ids: list[str], format: str, columns: list[str] | None,
                   title: str | None, project: str) -> tuple[str, str]:
    """
    Export results to the specified format.
    Returns (file_path, filename).
    """
    _ensure_export_dir()
    results = _collect_results(job_ids, project)
    if not results:
        raise ValueError("No results found for the specified job_ids")

    col_list, results = _filter_columns(results, columns)
    export_id = str(uuid.uuid4())[:12]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    if format == "csv":
        content = _to_csv(results, col_list)
        filename = f"export_{timestamp}.csv"
        filepath = os.path.join(settings.export_dir, f"{export_id}_{filename}")
        with open(filepath, "w") as f:
            f.write(content)

    elif format == "json":
        content = _to_json(results, col_list)
        filename = f"export_{timestamp}.json"
        filepath = os.path.join(settings.export_dir, f"{export_id}_{filename}")
        with open(filepath, "w") as f:
            f.write(content)

    elif format == "latex":
        content = _to_latex(results, col_list, title)
        filename = f"export_{timestamp}.tex"
        filepath = os.path.join(settings.export_dir, f"{export_id}_{filename}")
        with open(filepath, "w") as f:
            f.write(content)

    elif format == "pdf":
        content = _to_pdf(results, col_list, title)
        filename = f"export_{timestamp}.pdf"
        filepath = os.path.join(settings.export_dir, f"{export_id}_{filename}")
        with open(filepath, "wb") as f:
            f.write(content)

    else:
        raise ValueError(f"Unknown export format: {format}")

    return export_id, filepath, filename
