import {
  ReboundParams, PyscfParams, Psi4Params, GromacsParams, NamdParams,
  QmmmParams, MdanalysisParams, PybulletParams, EinsteinpyParams, NrpyParams,
  FenicsParams, ElmerParams, BasicoParams, TelluriumParams, Brian2Params,
  NestParams, MsprimeParams, RDKitParams, CanteraParams, QeParams,
  LammpsParams, SymPyParams, GmshParams, LcapyParams, PennyLaneParams,
  SagemathParams, Lean4Params, GapParams, PySpiceParams, QiskitParams,
  MatplotlibParams, ControlParams, PyomoParams, NetworkXParams, PhiFlowParams,
  ManimParams, OpenFOAMParams, DedalusParams, SU2Params, FiredrakeParams,
  VTKParams, OpenBabelParams, COMSOLParams, AlphaFoldParams, SLiMParams,
  TskitParams, SimuPOPParams, PyRosettaParams, EinsteinToolkitParams,
  RayOpticsParams, LightPipesParams, StrawberryFieldsParams, MeepParams,
  QutipParams, OpenmmParams,
} from './index';

export const PARAM_COMPONENTS = {
  rebound: ReboundParams,
  qutip: QutipParams,
  openmm: OpenmmParams,
  pyscf: PyscfParams,
  mdanalysis: MdanalysisParams,
  psi4: Psi4Params,
  gromacs: GromacsParams,
  namd: NamdParams,
  qmmm: QmmmParams,
  pybullet: PybulletParams,
  einsteinpy: EinsteinpyParams,
  nrpy: NrpyParams,
  fenics: FenicsParams,
  elmer: ElmerParams,
  basico: BasicoParams,
  tellurium: TelluriumParams,
  brian2: Brian2Params,
  nest: NestParams,
  msprime: MsprimeParams,
  rdkit: RDKitParams,
  cantera: CanteraParams,
  qe: QeParams,
  lammps: LammpsParams,
  sympy: SymPyParams,
  gmsh: GmshParams,
  lcapy: LcapyParams,
  pennylane: PennyLaneParams,
  sagemath: SagemathParams,
  lean4: Lean4Params,
  gap: GapParams,
  pyspice: PySpiceParams,
  qiskit: QiskitParams,
  matplotlib: MatplotlibParams,
  control: ControlParams,
  pyomo: PyomoParams,
  networkx: NetworkXParams,
  phiflow: PhiFlowParams,
  manim: ManimParams,
  openfoam: OpenFOAMParams,
  dedalus: DedalusParams,
  su2: SU2Params,
  firedrake: FiredrakeParams,
  vtk: VTKParams,
  openbabel: OpenBabelParams,
  comsol: COMSOLParams,
  alphafold: AlphaFoldParams,
  slim: SLiMParams,
  tskit: TskitParams,
  simupop: SimuPOPParams,
  pyrosetta: PyRosettaParams,
  einstein_toolkit: EinsteinToolkitParams,
  rayoptics: RayOpticsParams,
  lightpipes: LightPipesParams,
  strawberryfields: StrawberryFieldsParams,
  meep: MeepParams,
};
